# -*- coding: utf-8 -*-
# Banco de mensajes Orbita · PM Tool — 6 ejes × 15 = 90. (titular, remate naranja, subtítulo)
EJES = {
 "A": ("Portal integrado", "#OrbitaPMTool #GestiónDeProyectos #TuConsultor"),
 "B": ("Mejora ISO", "#ISO9001 #SistemasDeGestión #TuConsultor"),
 "C": ("Procesos y tareas", "#Procesos #Productividad #TuConsultor"),
 "D": ("Dashboard en tiempo real", "#Dashboard #Dirección #TuConsultor"),
 "E": ("Tu ISO en semanas", "#ISO9001 #Certificación #TuConsultor"),
 "F": ("Relación · Implicación · Compromiso", "#SistemasDeGestión #Consultoría #TuConsultor"),
}
CTA = {
 "A": ["Orbita · PM Tool, el portal de gestión de TuConsultor.", "Pide una demo de Orbita · PM Tool.", "Así trabajamos ahora con nuestros clientes.", "Un portal. Todo dentro. Orbita · PM Tool."],
 "B": ["Mantén tu ISO viva con Orbita · PM Tool.", "Tu sistema de gestión, semana a semana, en Orbita.", "Pide una demo y trae tu última no conformidad.", "Orbita · PM Tool: la ISO que no se oxida."],
 "C": ["Procesos con tareas, responsables y plazos. En Orbita.", "Pide una demo de Orbita · PM Tool.", "Cada proceso, sus tareas. Cada tarea, su dueño.", "Orbita · PM Tool: el mapa de procesos que ejecuta."],
 "D": ["Dashboard en tiempo real con Orbita · PM Tool.", "Pide una demo y mira tus proyectos en vivo.", "Orbita · PM Tool: ver es la mitad del control.", "Tu cliente lo ve. Tú lo ves. Nadie pregunta."],
 "E": ["Tu ISO en semanas, en un portal controlado. TuConsultor + Orbita.", "Pide el plan por semanas de tu certificación.", "Semanas contadas, hitos con evidencia. Orbita · PM Tool.", "Certificación ordenada, no exprés. Con método TuConsultor."],
 "F": ["Relación, Implicación o Compromiso: elige cuánto nos metemos.", "Sistemas de gestión con acompañamiento a medida. TuConsultor desde 2006.", "Pide una conversación de 20 minutos y te decimos qué modelo te encaja.", "Un sistema que dura, no un certificado que caduca."],
}
BANCO = {
"A": [
("Calidad en un Excel. Proyectos en otro.","Así no se gestiona. Se sobrevive.","Orbita · PM Tool: toda la gestión en un solo portal."),
("Un portal. Todos los proyectos. Todo el equipo.","Y el cliente dentro.","Se acabó el \"te lo paso por correo\"."),
("Cuatro carpetas, tres Drive y un WhatsApp.","Eso no es un sistema.","Un portal donde todo tiene sitio y dueño."),
("La versión buena del procedimiento","está en el portátil de alguien.","En Orbita hay una versión. La vigente."),
("\"¿Dónde está el último informe?\"","Pregunta prohibida desde hoy.","Documentos, hitos y tareas en el mismo sitio."),
("Tu consultor, tu equipo y tu auditor","mirando la misma pantalla.","Un portal, tres puntos de vista, cero sorpresas."),
("Integrar no es tener más pestañas.","Es tener menos preguntas.","Orbita une proyectos, procesos y evidencias."),
("Cada herramienta nueva que añades","resta una hora a la semana.","Una sola. Con todo dentro."),
("El correo no es un gestor de proyectos.","Nunca lo fue.","Orbita · PM Tool sí."),
("Lo que no está en el portal","no existe.","Y eso es exactamente lo que quieres."),
("Reunión de seguimiento de 90 minutos","para descubrir qué falta.","El portal ya lo sabía el lunes."),
("Cliente, consultor y equipo","en la misma órbita.","Gestión compartida, no repartida."),
("No necesitas más disciplina.","Necesitas un sitio.","Orbita pone el sitio. La disciplina viene sola."),
("Arrancar un proyecto nuevo:","15 minutos.","Plantilla, hitos, equipo y a trabajar."),
("Deja de gestionar de memoria.","Empieza a gestionar por portal.","Todo queda. Todo se ve."),
],
"B": [
("Tu ISO no falla en la auditoría.","Falla los otros 364 días.","Con Orbita el sistema se mantiene cada semana, no la víspera."),
("No conformidad abierta 8 meses. Nadie la vio.","Nadie la buscó.","Cada acción con dueño, fecha y evidencia. A la vista."),
("El sistema de gestión no es la carpeta.","Es lo que pasa cada semana.","Orbita lo convierte en rutina."),
("Auditoría interna en octubre.","Evidencias desde enero.","Registrar en el momento, no la víspera."),
("Acción correctiva sin fecha de cierre","no es una acción. Es una intención.","Orbita no deja intenciones abiertas."),
("Tres normas. Un sistema.","Cero duplicados.","9001, 14001 y 45001 comparten órbita."),
("La revisión por la dirección","ya no se prepara. Se abre.","Los datos llevan meses acumulándose solos."),
("Indicadores que se actualizan solos","son indicadores que se miran.","Los que se calculan a mano, no."),
("El auditor pregunta.","Tú le enseñas la pantalla.","Y se acaba la conversación."),
("Tu certificado se renueva cada tres años.","Tu sistema, cada semana.","O no es un sistema."),
("\"Lo tenemos, pero hay que buscarlo\"","es la frase que más cuesta en una auditoría.","Orbita la elimina."),
("Riesgos con dueño.","Oportunidades con fecha.","Lo demás es una matriz decorativa."),
("Formación registrada, competencia evaluada,","evidencia guardada.","Automáticamente. No \"cuando pueda\"."),
("El 80 % de las no conformidades se repiten.","Porque nadie mira las anteriores.","Orbita sí las mira. Y te avisa."),
("ISO no es papeleo.","Es saber qué pasa antes de que pase.","Con un sistema que avisa, no que archiva."),
],
"C": [
("Sabes qué hay que hacer. Lo que no sabes es","quién lo está haciendo.","Procesos con tareas, responsables y plazos que se ven."),
("\"Lo tengo pendiente\" no es un estado.","Es una alarma.","Tareas por proceso, cada una con su semáforo."),
("El procedimiento dice qué.","Orbita dice quién y cuándo.","Cada proceso con sus tareas asignadas."),
("Un proceso sin tareas","es un dibujo.","Orbita lo convierte en trabajo."),
("Tarea vencida tres días.","Nadie preguntó. Nadie avisó.","Ahora avisa Orbita."),
("Delegar no es decirlo en la reunión.","Es asignarlo, con fecha.","Y ver cuándo se hace."),
("Diez personas, treinta procesos,","doscientas tareas.","Una pantalla. Ningún hilo de correo."),
("Cuando todo es urgente","nada lo es.","Prioridad por proceso, no por quien más grita."),
("Lo que se mide con semáforo","se hace antes del rojo.","Verde, ámbar, rojo. Y ya."),
("El mapa de procesos colgado en la pared","no ejecuta nada.","El de Orbita, sí."),
("\"¿Quién lleva esto?\"","Nunca más en un correo.","Está en la tarea. Desde que se creó."),
("Cada proceso deja rastro:","qué, quién, cuándo, evidencia.","Sin pedírselo a nadie."),
("Calibración, revisión, formación.","Se crean solas. No se olvidan solas.","Tareas recurrentes con dueño y fecha."),
("Carga de trabajo real, por persona.","Antes de que alguien reviente.","No después."),
("Controlar el proceso no es vigilar a la gente.","Es que nadie persiga a nadie.","Orbita lo hace por ti."),
],
"D": [
("¿Cómo va el proyecto? Ya no es una pregunta.","Es una pantalla.","Evolución en tiempo real. Sin pedir informes."),
("El informe de seguimiento del lunes","ya estaba viejo el martes.","Dashboard en tiempo real. Para ti y para tu cliente."),
("Un dashboard que se actualiza solo","es una reunión menos.","Por semana. Cada semana."),
("Verde, ámbar, rojo.","Por proyecto, por hito, por persona.","Ahora. No a final de mes."),
("Tu cliente ve el avance","antes de preguntarlo.","Y deja de preguntarlo."),
("El porcentaje de avance real,","no el que se dice en la reunión.","Calculado con lo que está hecho."),
("Todos los proyectos en una pantalla.","Los que van mal, primero.","Prioridad automática."),
("Hitos cumplidos, retrasados, en riesgo.","En una sola vista.","Cada mañana, sin abrir un Excel."),
("Dirección no quiere leer informes.","Quiere ver semáforos.","Dashboard para quien decide."),
("Lo que no se ve","no se corrige a tiempo.","Ver es la mitad del control."),
("Desviación de plazo detectada hoy.","No en el comité del mes que viene.","Ese mes es la diferencia."),
("Tiempo real no es un lujo.","Es dejar de decidir con datos viejos.","Orbita muestra lo que hay. Ahora."),
("Un dashboard por cliente.","Uno global para ti.","Los dos, en vivo."),
("Deja de preparar el PowerPoint del estado del proyecto.","Comparte la pantalla.","Ya está preparado."),
("El proyecto no avanza porque lo mires.","Pero se desvía cuando no lo miras.","Míralo cada día. En 30 segundos."),
],
"E": [
("Tu ISO en semanas.","No en un año de reuniones.","Portal controlado, plan cerrado, fechas a la vista."),
("ISO 9001 desde cero:","12 semanas, un portal, un plan.","Cada semana sabes qué toca. Y quién."),
("Certificarse no es lento.","Es desordenado.","Ordénalo en un portal y mira lo que tarda."),
("Semana 1: alcance. Semana 12: auditoría.","Entre medias, nada al aire.","Todo en Orbita."),
("Un portal controlado significa","que nadie improvisa.","Ni tú, ni tu equipo, ni tu consultor."),
("Sabes en qué semana estás","y cuántas faltan.","Sin preguntarlo. Sin adivinarlo."),
("Tu sistema, tu documentación, tus evidencias.","En tu portal. Con control de acceso.","No en el ordenador de nadie."),
("La certificación exprés no existe.","La certificación ordenada, sí.","Semanas, no meses. Con método."),
("Cada semana un hito cerrado.","Cada hito con evidencia.","Y la auditoría deja de dar miedo."),
("Empezar una ISO sin plan por semanas","es empezar a alargarla.","Orbita trae el plan hecho."),
("Control no es vigilancia.","Es saber que el jueves estará hecho.","Porque está asignado y se ve."),
("¿Cuánto tarda una ISO?","Lo que tarde la semana más lenta.","Orbita te dice cuál es. Y por qué."),
("El portal es tuyo.","El método, de TuConsultor.","Las semanas, contadas."),
("Documentos versionados, accesos por rol,","evidencias con fecha.","Un portal que aguanta una auditoría."),
("Tu ISO en semanas","es una promesa que se puede ver.","Semana a semana. En Orbita."),
],
"F": [
("Relación, Implicación o Compromiso.","Tres formas de trabajar contigo.","Una herramienta para las tres."),
("Relación: te acompañamos. Implicación: lo hacemos contigo.","Compromiso: lo hacemos y respondemos.","Tú eliges la distancia."),
("No vendemos horas.","Vendemos un sistema que funciona.","Y un modelo de relación que lo mantiene."),
("Tu sistema de gestión no es un proyecto.","Es una relación.","Elige cuánta implicación necesitas."),
("Con Relación, el sistema es tuyo y nosotros cerca.","Con Compromiso, nosotros dentro.","Tú decides."),
("Veinte años implantando sistemas","enseñan una cosa:","el modelo de trabajo importa más que la norma."),
("9001, 14001, 45001, 27001, EFQM.","Distintas normas, mismo portal.","Mismo modelo de trabajo."),
("Implicación: reuniones semanales, hitos compartidos,","portal común.","Ni más ni menos de lo que necesitas."),
("Compromiso es que respondemos","del sistema en la auditoría.","Contigo. En la sala."),
("Un sistema de gestión sin acompañamiento","envejece en un año.","Con modelo de relación, madura."),
("Desde 2006 gestionamos con corazón.","Desde ahora, también con órbita.","Sistemas de gestión con acompañamiento a medida."),
("No todos los clientes necesitan lo mismo.","Por eso hay tres modelos.","Y solo uno es el tuyo."),
("Un buen sistema de gestión:","menos incendios, más decisiones.","TuConsultor: que dure."),
("Relación · Implicación · Compromiso.","Sube o baja cuando quieras.","El portal sigue siendo el mismo."),
("Un sistema bien acompañado","se nota en la cuenta de resultados.","No solo en el certificado."),
],
}
assert all(len(v)==15 for v in BANCO.values())
