-- ═══════════════════════════════════════════════════════════════════════════
-- v117 · ISO/IEC 27701 · GESTIÓN DE LA PRIVACIDAD DE LA INFORMACIÓN
--
-- Va detrás de la v116. Añade la norma al catálogo de Órbita:
--
--   · `normas_catalogo`: ISO 27701, nivel J2, 55 h de apoyo. Es la extensión
--     de privacidad de ISO 27001/27002 (Sistema de Gestión de la Información
--     de Privacidad, SGIC): exige un SGSI en el que apoyarse, así que en la
--     app va marcada como complementaria de 27001 (`solapeCon`) y cuesta menos
--     cuando se contrata junto a ella.
--   · `tareas_catalogo`: 20 tareas por modelo (Apoyo, Relación, Implicación,
--     Compromiso, Implantación). Las del mapa de procesos común (PE1–PE3, PA1,
--     PA3, PA5, PA6) llevan en la descripción lo que 27701 añade al SGSI; las
--     cinco de PA19 «Gestión de la privacidad» son las propias de la norma:
--     registro de tratamientos, EIPD, derechos, brechas y transferencias.
--   · `codigo_proyecto`: la abreviatura «277» para el código de proyecto
--     (CLIE-2026-REL-27-277). Sin esto salía igual por el caso por defecto,
--     pero conviene que esté explícita como las demás.
--
-- Horas por modelo: Apoyo y Relación 92 h · Implicación 116 h · Compromiso
-- 148 h · Implantación 55,2 h. Unas dos terceras partes de ISO 27001, que es
-- la proporción habitual de la extensión sobre la norma base.
-- ═══════════════════════════════════════════════════════════════════════════

insert into public.normas_catalogo (id, nombre, descripcion, nivel, h_apoyo, activa) values
  ('27701', 'ISO 27701', 'Gestión de la privacidad de la información · extensión de ISO 27001', 'J2', 55, true)
on conflict (id) do update
  set nombre = excluded.nombre, descripcion = excluded.descripcion,
      nivel = excluded.nivel, h_apoyo = excluded.h_apoyo, activa = excluded.activa;

-- Se relanza sin duplicar: si ya hubiera tareas de la 27701, se sustituyen.
delete from public.tareas_catalogo where norma_id = '27701';

insert into public.tareas_catalogo (norma_id, modelo, titulo, proceso, subproceso, horas_base, orden, descripcion) values
  ('27701','Apoyo','PE1 PLANIFICACIÓN ESTRATÉGICA - S1 PE1 GESTIÓN DEL CONTEXTO Y GI','PE1 PLANIFICACIÓN ESTRATÉGICA','S1 PE1 GESTIÓN DEL CONTEXTO Y GI',3,1,'Rol de la organización como responsable y/o encargado del tratamiento, partes interesadas con responsabilidades sobre datos personales y legislación aplicable (5.2.1–5.2.3).'),
  ('27701','Apoyo','PE1 PLANIFICACIÓN ESTRATÉGICA - S2 PE1 GESTIÓN DE RIESGOS','PE1 PLANIFICACIÓN ESTRATÉGICA','S2 PE1 GESTIÓN DE RIESGOS',8,2,'Riesgos para la privacidad integrados en el análisis de riesgos del SGSI; plan de tratamiento y declaración de aplicabilidad ampliada con los anexos A y B (5.4.1, 5.4.2).'),
  ('27701','Apoyo','PE1 PLANIFICACIÓN ESTRATÉGICA - S3 PE1 GESTIÓN DE EST, POLT Y OBJ','PE1 PLANIFICACIÓN ESTRATÉGICA','S3 PE1 GESTIÓN DE EST, POLT Y OBJ',6,3,'Política de privacidad, objetivos del SGIC y compromiso de la dirección; integración del SGIC en el SGSI (5.3, 5.4.2).'),
  ('27701','Apoyo','PE2 EVALUACIÓN DESEMPEÑO - S1 PE2 ANÁLISIS DE DATOS','PE2 EVALUACIÓN DESEMPEÑO','S1 PE2 ANÁLISIS DE DATOS',4,4,'Indicadores del SGIC: solicitudes de derechos y plazos de respuesta, brechas, evaluaciones de impacto realizadas (5.7.1).'),
  ('27701','Apoyo','PE2 EVALUACIÓN DESEMPEÑO - S2 PE2 AUDITORÍA INTERNA','PE2 EVALUACIÓN DESEMPEÑO','S2 PE2 AUDITORÍA INTERNA',6,5,'Auditoría interna del SGIC, incluidos los controles de los anexos A (responsable) y B (encargado) (5.7.2).'),
  ('27701','Apoyo','PE2 EVALUACIÓN DESEMPEÑO - S3 PE2 REVISIÓN POR LA DIRECCIÓN','PE2 EVALUACIÓN DESEMPEÑO','S3 PE2 REVISIÓN POR LA DIRECCIÓN',3,6,'Revisión por la dirección con las entradas de privacidad: derechos, brechas, autoridades de control, cambios legales (5.7.3).'),
  ('27701','Apoyo','PE3 MEJORA CONTINUA - S1 PE3 GESTIÓN DE NO CONFORMIDADES','PE3 MEJORA CONTINUA','S1 PE3 GESTIÓN DE NO CONFORMIDADES',3,7,'No conformidades y acciones correctivas del SGIC; mejora continua (5.8).'),
  ('27701','Apoyo','PA1 GESTIÓN DE PERSONAS - S1 PA1 GESTIÓN DE PUESTOS Y ROLES','PA1 GESTIÓN DE PERSONAS','S1 PA1 GESTIÓN DE PUESTOS Y ROLES',4,8,'Roles y responsabilidades de privacidad: delegado de protección de datos o responsable de privacidad, propietarios de cada tratamiento (6.3.1.1, 7.2.1).'),
  ('27701','Apoyo','PA1 GESTIÓN DE PERSONAS - S2 PA1 DESARROLLO PERSONAS','PA1 GESTIÓN DE PERSONAS','S2 PA1 DESARROLLO PERSONAS',4,9,'Competencia y concienciación del personal en protección de datos; formación específica por rol (5.5.2, 5.5.3, 6.4.2).'),
  ('27701','Apoyo','PA3 GESTIÓN DEL CONOCIMIENTO - S1 PA3 GESTIÓN INFORMAC. DOC.','PA3 GESTIÓN DEL CONOCIMIENTO','S1 PA3 GESTIÓN INFORMAC. DOC.',4,10,'Documentación del SGIC: procedimientos, registros y evidencias exigidas por la norma (5.5.5).'),
  ('27701','Apoyo','PA3 GESTIÓN DEL CONOCIMIENTO - S2 PA3 CONTROL LEGAL','PA3 GESTIÓN DEL CONOCIMIENTO','S2 PA3 CONTROL LEGAL',4,11,'Identificación y seguimiento de la legislación de protección de datos aplicable: RGPD, LOPDGDD, normativa sectorial y criterios de la AEPD (5.2.1, 7.2.2).'),
  ('27701','Apoyo','PA5 GESTIÓN DE SEGURIDAD - S1 PA5 GESTION SEGURIDAD OPERACIONAL','PA5 GESTIÓN DE SEGURIDAD','S1 PA5 GESTION SEGURIDAD OPERACIONAL',5,12,'Controles de ISO 27002 extendidos a los datos personales: clasificación, soportes, borrado seguro, registro y supervisión (6.5, 6.8, 6.9).'),
  ('27701','Apoyo','PA5 GESTIÓN DE SEGURIDAD - S2 PA5 GESTION SEGURIDAD LÓGICA','PA5 GESTIÓN DE SEGURIDAD','S2 PA5 GESTION SEGURIDAD LÓGICA',5,13,'Control de acceso a datos personales, cifrado, minimización y seudonimización, registros de acceso (6.6, 6.7, 6.10, 7.4).'),
  ('27701','Apoyo','PA6 GESTIÓN DE PARTES SUBCONTRATADAS - S1 PA6 HOMOLOGACIÓN PROVEEDORES','PA6 GESTIÓN DE PARTES SUBCONTRATADAS','S1 PA6 HOMOLOGACIÓN PROVEEDORES',3,14,'Encargados y subencargados del tratamiento: contratos, garantías y cláusulas de protección de datos (7.2.6, 8.2, 8.5.6–8.5.8).'),
  ('27701','Apoyo','PA6 GESTIÓN DE PARTES SUBCONTRATADAS - S2 PA6 EVALUACIÓN PROVEEDORES','PA6 GESTIÓN DE PARTES SUBCONTRATADAS','S2 PA6 EVALUACIÓN PROVEEDORES',2,15,'Supervisión de encargados y subencargados; evidencias de cumplimiento (8.5).'),
  ('27701','Apoyo','PA19 GESTIÓN DE LA PRIVACIDAD - S1 PA19 REGISTRO DE TRATAMIENTOS Y BASES DE LEGITIMACIÓN (7.2.2, 7.2.8)','PA19 GESTIÓN DE LA PRIVACIDAD','S1 PA19 REGISTRO DE TRATAMIENTOS Y BASES DE LEGITIMACIÓN (7.2.2, 7.2.8)',8,16,'Inventario de actividades de tratamiento: finalidad, base de legitimación, consentimiento, categorías de datos, plazos de conservación.'),
  ('27701','Apoyo','PA19 GESTIÓN DE LA PRIVACIDAD - S2 PA19 EVALUACIONES DE IMPACTO Y PRIVACIDAD DESDE EL DISEÑO (7.2.5, 7.4)','PA19 GESTIÓN DE LA PRIVACIDAD','S2 PA19 EVALUACIONES DE IMPACTO Y PRIVACIDAD DESDE EL DISEÑO (7.2.5, 7.4)',6,17,'Metodología y realización de evaluaciones de impacto (EIPD); privacidad desde el diseño y por defecto en nuevos tratamientos y sistemas.'),
  ('27701','Apoyo','PA19 GESTIÓN DE LA PRIVACIDAD - S3 PA19 INFORMACIÓN Y DERECHOS DE LOS INTERESADOS (7.3)','PA19 GESTIÓN DE LA PRIVACIDAD','S3 PA19 INFORMACIÓN Y DERECHOS DE LOS INTERESADOS (7.3)',6,18,'Cláusulas informativas y procedimiento de atención de derechos: acceso, rectificación, supresión, portabilidad, oposición y limitación, con sus plazos.'),
  ('27701','Apoyo','PA19 GESTIÓN DE LA PRIVACIDAD - S4 PA19 GESTIÓN DE BRECHAS DE DATOS PERSONALES (6.13.1)','PA19 GESTIÓN DE LA PRIVACIDAD','S4 PA19 GESTIÓN DE BRECHAS DE DATOS PERSONALES (6.13.1)',5,19,'Detección, registro y evaluación de brechas; notificación a la autoridad de control en 72 horas y comunicación a los interesados cuando proceda.'),
  ('27701','Apoyo','PA19 GESTIÓN DE LA PRIVACIDAD - S5 PA19 TRANSFERENCIAS Y COMUNICACIÓN A TERCEROS (7.5, 8.5)','PA19 GESTIÓN DE LA PRIVACIDAD','S5 PA19 TRANSFERENCIAS Y COMUNICACIÓN A TERCEROS (7.5, 8.5)',3,20,'Transferencias internacionales y comunicaciones de datos: garantías, cláusulas contractuales tipo, registro de destinatarios.'),
  ('27701','Relación','PE1 PLANIFICACIÓN ESTRATÉGICA - S1 PE1 GESTIÓN DEL CONTEXTO Y GI','PE1 PLANIFICACIÓN ESTRATÉGICA','S1 PE1 GESTIÓN DEL CONTEXTO Y GI',3,1,'Rol de la organización como responsable y/o encargado del tratamiento, partes interesadas con responsabilidades sobre datos personales y legislación aplicable (5.2.1–5.2.3).'),
  ('27701','Relación','PE1 PLANIFICACIÓN ESTRATÉGICA - S2 PE1 GESTIÓN DE RIESGOS','PE1 PLANIFICACIÓN ESTRATÉGICA','S2 PE1 GESTIÓN DE RIESGOS',8,2,'Riesgos para la privacidad integrados en el análisis de riesgos del SGSI; plan de tratamiento y declaración de aplicabilidad ampliada con los anexos A y B (5.4.1, 5.4.2).'),
  ('27701','Relación','PE1 PLANIFICACIÓN ESTRATÉGICA - S3 PE1 GESTIÓN DE EST, POLT Y OBJ','PE1 PLANIFICACIÓN ESTRATÉGICA','S3 PE1 GESTIÓN DE EST, POLT Y OBJ',6,3,'Política de privacidad, objetivos del SGIC y compromiso de la dirección; integración del SGIC en el SGSI (5.3, 5.4.2).'),
  ('27701','Relación','PE2 EVALUACIÓN DESEMPEÑO - S1 PE2 ANÁLISIS DE DATOS','PE2 EVALUACIÓN DESEMPEÑO','S1 PE2 ANÁLISIS DE DATOS',4,4,'Indicadores del SGIC: solicitudes de derechos y plazos de respuesta, brechas, evaluaciones de impacto realizadas (5.7.1).'),
  ('27701','Relación','PE2 EVALUACIÓN DESEMPEÑO - S2 PE2 AUDITORÍA INTERNA','PE2 EVALUACIÓN DESEMPEÑO','S2 PE2 AUDITORÍA INTERNA',6,5,'Auditoría interna del SGIC, incluidos los controles de los anexos A (responsable) y B (encargado) (5.7.2).'),
  ('27701','Relación','PE2 EVALUACIÓN DESEMPEÑO - S3 PE2 REVISIÓN POR LA DIRECCIÓN','PE2 EVALUACIÓN DESEMPEÑO','S3 PE2 REVISIÓN POR LA DIRECCIÓN',3,6,'Revisión por la dirección con las entradas de privacidad: derechos, brechas, autoridades de control, cambios legales (5.7.3).'),
  ('27701','Relación','PE3 MEJORA CONTINUA - S1 PE3 GESTIÓN DE NO CONFORMIDADES','PE3 MEJORA CONTINUA','S1 PE3 GESTIÓN DE NO CONFORMIDADES',3,7,'No conformidades y acciones correctivas del SGIC; mejora continua (5.8).'),
  ('27701','Relación','PA1 GESTIÓN DE PERSONAS - S1 PA1 GESTIÓN DE PUESTOS Y ROLES','PA1 GESTIÓN DE PERSONAS','S1 PA1 GESTIÓN DE PUESTOS Y ROLES',4,8,'Roles y responsabilidades de privacidad: delegado de protección de datos o responsable de privacidad, propietarios de cada tratamiento (6.3.1.1, 7.2.1).'),
  ('27701','Relación','PA1 GESTIÓN DE PERSONAS - S2 PA1 DESARROLLO PERSONAS','PA1 GESTIÓN DE PERSONAS','S2 PA1 DESARROLLO PERSONAS',4,9,'Competencia y concienciación del personal en protección de datos; formación específica por rol (5.5.2, 5.5.3, 6.4.2).'),
  ('27701','Relación','PA3 GESTIÓN DEL CONOCIMIENTO - S1 PA3 GESTIÓN INFORMAC. DOC.','PA3 GESTIÓN DEL CONOCIMIENTO','S1 PA3 GESTIÓN INFORMAC. DOC.',4,10,'Documentación del SGIC: procedimientos, registros y evidencias exigidas por la norma (5.5.5).'),
  ('27701','Relación','PA3 GESTIÓN DEL CONOCIMIENTO - S2 PA3 CONTROL LEGAL','PA3 GESTIÓN DEL CONOCIMIENTO','S2 PA3 CONTROL LEGAL',4,11,'Identificación y seguimiento de la legislación de protección de datos aplicable: RGPD, LOPDGDD, normativa sectorial y criterios de la AEPD (5.2.1, 7.2.2).'),
  ('27701','Relación','PA5 GESTIÓN DE SEGURIDAD - S1 PA5 GESTION SEGURIDAD OPERACIONAL','PA5 GESTIÓN DE SEGURIDAD','S1 PA5 GESTION SEGURIDAD OPERACIONAL',5,12,'Controles de ISO 27002 extendidos a los datos personales: clasificación, soportes, borrado seguro, registro y supervisión (6.5, 6.8, 6.9).'),
  ('27701','Relación','PA5 GESTIÓN DE SEGURIDAD - S2 PA5 GESTION SEGURIDAD LÓGICA','PA5 GESTIÓN DE SEGURIDAD','S2 PA5 GESTION SEGURIDAD LÓGICA',5,13,'Control de acceso a datos personales, cifrado, minimización y seudonimización, registros de acceso (6.6, 6.7, 6.10, 7.4).'),
  ('27701','Relación','PA6 GESTIÓN DE PARTES SUBCONTRATADAS - S1 PA6 HOMOLOGACIÓN PROVEEDORES','PA6 GESTIÓN DE PARTES SUBCONTRATADAS','S1 PA6 HOMOLOGACIÓN PROVEEDORES',3,14,'Encargados y subencargados del tratamiento: contratos, garantías y cláusulas de protección de datos (7.2.6, 8.2, 8.5.6–8.5.8).'),
  ('27701','Relación','PA6 GESTIÓN DE PARTES SUBCONTRATADAS - S2 PA6 EVALUACIÓN PROVEEDORES','PA6 GESTIÓN DE PARTES SUBCONTRATADAS','S2 PA6 EVALUACIÓN PROVEEDORES',2,15,'Supervisión de encargados y subencargados; evidencias de cumplimiento (8.5).'),
  ('27701','Relación','PA19 GESTIÓN DE LA PRIVACIDAD - S1 PA19 REGISTRO DE TRATAMIENTOS Y BASES DE LEGITIMACIÓN (7.2.2, 7.2.8)','PA19 GESTIÓN DE LA PRIVACIDAD','S1 PA19 REGISTRO DE TRATAMIENTOS Y BASES DE LEGITIMACIÓN (7.2.2, 7.2.8)',8,16,'Inventario de actividades de tratamiento: finalidad, base de legitimación, consentimiento, categorías de datos, plazos de conservación.'),
  ('27701','Relación','PA19 GESTIÓN DE LA PRIVACIDAD - S2 PA19 EVALUACIONES DE IMPACTO Y PRIVACIDAD DESDE EL DISEÑO (7.2.5, 7.4)','PA19 GESTIÓN DE LA PRIVACIDAD','S2 PA19 EVALUACIONES DE IMPACTO Y PRIVACIDAD DESDE EL DISEÑO (7.2.5, 7.4)',6,17,'Metodología y realización de evaluaciones de impacto (EIPD); privacidad desde el diseño y por defecto en nuevos tratamientos y sistemas.'),
  ('27701','Relación','PA19 GESTIÓN DE LA PRIVACIDAD - S3 PA19 INFORMACIÓN Y DERECHOS DE LOS INTERESADOS (7.3)','PA19 GESTIÓN DE LA PRIVACIDAD','S3 PA19 INFORMACIÓN Y DERECHOS DE LOS INTERESADOS (7.3)',6,18,'Cláusulas informativas y procedimiento de atención de derechos: acceso, rectificación, supresión, portabilidad, oposición y limitación, con sus plazos.'),
  ('27701','Relación','PA19 GESTIÓN DE LA PRIVACIDAD - S4 PA19 GESTIÓN DE BRECHAS DE DATOS PERSONALES (6.13.1)','PA19 GESTIÓN DE LA PRIVACIDAD','S4 PA19 GESTIÓN DE BRECHAS DE DATOS PERSONALES (6.13.1)',5,19,'Detección, registro y evaluación de brechas; notificación a la autoridad de control en 72 horas y comunicación a los interesados cuando proceda.'),
  ('27701','Relación','PA19 GESTIÓN DE LA PRIVACIDAD - S5 PA19 TRANSFERENCIAS Y COMUNICACIÓN A TERCEROS (7.5, 8.5)','PA19 GESTIÓN DE LA PRIVACIDAD','S5 PA19 TRANSFERENCIAS Y COMUNICACIÓN A TERCEROS (7.5, 8.5)',3,20,'Transferencias internacionales y comunicaciones de datos: garantías, cláusulas contractuales tipo, registro de destinatarios.'),
  ('27701','Implicación','PE1 PLANIFICACIÓN ESTRATÉGICA - S1 PE1 GESTIÓN DEL CONTEXTO Y GI','PE1 PLANIFICACIÓN ESTRATÉGICA','S1 PE1 GESTIÓN DEL CONTEXTO Y GI',3,1,'Rol de la organización como responsable y/o encargado del tratamiento, partes interesadas con responsabilidades sobre datos personales y legislación aplicable (5.2.1–5.2.3).'),
  ('27701','Implicación','PE1 PLANIFICACIÓN ESTRATÉGICA - S2 PE1 GESTIÓN DE RIESGOS','PE1 PLANIFICACIÓN ESTRATÉGICA','S2 PE1 GESTIÓN DE RIESGOS',8,2,'Riesgos para la privacidad integrados en el análisis de riesgos del SGSI; plan de tratamiento y declaración de aplicabilidad ampliada con los anexos A y B (5.4.1, 5.4.2).'),
  ('27701','Implicación','PE1 PLANIFICACIÓN ESTRATÉGICA - S3 PE1 GESTIÓN DE EST, POLT Y OBJ','PE1 PLANIFICACIÓN ESTRATÉGICA','S3 PE1 GESTIÓN DE EST, POLT Y OBJ',6,3,'Política de privacidad, objetivos del SGIC y compromiso de la dirección; integración del SGIC en el SGSI (5.3, 5.4.2).'),
  ('27701','Implicación','PE2 EVALUACIÓN DESEMPEÑO - S1 PE2 ANÁLISIS DE DATOS','PE2 EVALUACIÓN DESEMPEÑO','S1 PE2 ANÁLISIS DE DATOS',4,4,'Indicadores del SGIC: solicitudes de derechos y plazos de respuesta, brechas, evaluaciones de impacto realizadas (5.7.1).'),
  ('27701','Implicación','PE2 EVALUACIÓN DESEMPEÑO - S2 PE2 AUDITORÍA INTERNA','PE2 EVALUACIÓN DESEMPEÑO','S2 PE2 AUDITORÍA INTERNA',10,5,'Auditoría interna del SGIC, incluidos los controles de los anexos A (responsable) y B (encargado) (5.7.2).'),
  ('27701','Implicación','PE2 EVALUACIÓN DESEMPEÑO - S3 PE2 REVISIÓN POR LA DIRECCIÓN','PE2 EVALUACIÓN DESEMPEÑO','S3 PE2 REVISIÓN POR LA DIRECCIÓN',4,6,'Revisión por la dirección con las entradas de privacidad: derechos, brechas, autoridades de control, cambios legales (5.7.3).'),
  ('27701','Implicación','PE3 MEJORA CONTINUA - S1 PE3 GESTIÓN DE NO CONFORMIDADES','PE3 MEJORA CONTINUA','S1 PE3 GESTIÓN DE NO CONFORMIDADES',3,7,'No conformidades y acciones correctivas del SGIC; mejora continua (5.8).'),
  ('27701','Implicación','PA1 GESTIÓN DE PERSONAS - S1 PA1 GESTIÓN DE PUESTOS Y ROLES','PA1 GESTIÓN DE PERSONAS','S1 PA1 GESTIÓN DE PUESTOS Y ROLES',4,8,'Roles y responsabilidades de privacidad: delegado de protección de datos o responsable de privacidad, propietarios de cada tratamiento (6.3.1.1, 7.2.1).'),
  ('27701','Implicación','PA1 GESTIÓN DE PERSONAS - S2 PA1 DESARROLLO PERSONAS','PA1 GESTIÓN DE PERSONAS','S2 PA1 DESARROLLO PERSONAS',8,9,'Competencia y concienciación del personal en protección de datos; formación específica por rol (5.5.2, 5.5.3, 6.4.2).'),
  ('27701','Implicación','PA3 GESTIÓN DEL CONOCIMIENTO - S1 PA3 GESTIÓN INFORMAC. DOC.','PA3 GESTIÓN DEL CONOCIMIENTO','S1 PA3 GESTIÓN INFORMAC. DOC.',4,10,'Documentación del SGIC: procedimientos, registros y evidencias exigidas por la norma (5.5.5).'),
  ('27701','Implicación','PA3 GESTIÓN DEL CONOCIMIENTO - S2 PA3 CONTROL LEGAL','PA3 GESTIÓN DEL CONOCIMIENTO','S2 PA3 CONTROL LEGAL',6,11,'Identificación y seguimiento de la legislación de protección de datos aplicable: RGPD, LOPDGDD, normativa sectorial y criterios de la AEPD (5.2.1, 7.2.2).'),
  ('27701','Implicación','PA5 GESTIÓN DE SEGURIDAD - S1 PA5 GESTION SEGURIDAD OPERACIONAL','PA5 GESTIÓN DE SEGURIDAD','S1 PA5 GESTION SEGURIDAD OPERACIONAL',6,12,'Controles de ISO 27002 extendidos a los datos personales: clasificación, soportes, borrado seguro, registro y supervisión (6.5, 6.8, 6.9).'),
  ('27701','Implicación','PA5 GESTIÓN DE SEGURIDAD - S2 PA5 GESTION SEGURIDAD LÓGICA','PA5 GESTIÓN DE SEGURIDAD','S2 PA5 GESTION SEGURIDAD LÓGICA',5,13,'Control de acceso a datos personales, cifrado, minimización y seudonimización, registros de acceso (6.6, 6.7, 6.10, 7.4).'),
  ('27701','Implicación','PA6 GESTIÓN DE PARTES SUBCONTRATADAS - S1 PA6 HOMOLOGACIÓN PROVEEDORES','PA6 GESTIÓN DE PARTES SUBCONTRATADAS','S1 PA6 HOMOLOGACIÓN PROVEEDORES',4,14,'Encargados y subencargados del tratamiento: contratos, garantías y cláusulas de protección de datos (7.2.6, 8.2, 8.5.6–8.5.8).'),
  ('27701','Implicación','PA6 GESTIÓN DE PARTES SUBCONTRATADAS - S2 PA6 EVALUACIÓN PROVEEDORES','PA6 GESTIÓN DE PARTES SUBCONTRATADAS','S2 PA6 EVALUACIÓN PROVEEDORES',3,15,'Supervisión de encargados y subencargados; evidencias de cumplimiento (8.5).'),
  ('27701','Implicación','PA19 GESTIÓN DE LA PRIVACIDAD - S1 PA19 REGISTRO DE TRATAMIENTOS Y BASES DE LEGITIMACIÓN (7.2.2, 7.2.8)','PA19 GESTIÓN DE LA PRIVACIDAD','S1 PA19 REGISTRO DE TRATAMIENTOS Y BASES DE LEGITIMACIÓN (7.2.2, 7.2.8)',10,16,'Inventario de actividades de tratamiento: finalidad, base de legitimación, consentimiento, categorías de datos, plazos de conservación.'),
  ('27701','Implicación','PA19 GESTIÓN DE LA PRIVACIDAD - S2 PA19 EVALUACIONES DE IMPACTO Y PRIVACIDAD DESDE EL DISEÑO (7.2.5, 7.4)','PA19 GESTIÓN DE LA PRIVACIDAD','S2 PA19 EVALUACIONES DE IMPACTO Y PRIVACIDAD DESDE EL DISEÑO (7.2.5, 7.4)',8,17,'Metodología y realización de evaluaciones de impacto (EIPD); privacidad desde el diseño y por defecto en nuevos tratamientos y sistemas.'),
  ('27701','Implicación','PA19 GESTIÓN DE LA PRIVACIDAD - S3 PA19 INFORMACIÓN Y DERECHOS DE LOS INTERESADOS (7.3)','PA19 GESTIÓN DE LA PRIVACIDAD','S3 PA19 INFORMACIÓN Y DERECHOS DE LOS INTERESADOS (7.3)',8,18,'Cláusulas informativas y procedimiento de atención de derechos: acceso, rectificación, supresión, portabilidad, oposición y limitación, con sus plazos.'),
  ('27701','Implicación','PA19 GESTIÓN DE LA PRIVACIDAD - S4 PA19 GESTIÓN DE BRECHAS DE DATOS PERSONALES (6.13.1)','PA19 GESTIÓN DE LA PRIVACIDAD','S4 PA19 GESTIÓN DE BRECHAS DE DATOS PERSONALES (6.13.1)',8,19,'Detección, registro y evaluación de brechas; notificación a la autoridad de control en 72 horas y comunicación a los interesados cuando proceda.'),
  ('27701','Implicación','PA19 GESTIÓN DE LA PRIVACIDAD - S5 PA19 TRANSFERENCIAS Y COMUNICACIÓN A TERCEROS (7.5, 8.5)','PA19 GESTIÓN DE LA PRIVACIDAD','S5 PA19 TRANSFERENCIAS Y COMUNICACIÓN A TERCEROS (7.5, 8.5)',4,20,'Transferencias internacionales y comunicaciones de datos: garantías, cláusulas contractuales tipo, registro de destinatarios.'),
  ('27701','Compromiso','PE1 PLANIFICACIÓN ESTRATÉGICA - S1 PE1 GESTIÓN DEL CONTEXTO Y GI','PE1 PLANIFICACIÓN ESTRATÉGICA','S1 PE1 GESTIÓN DEL CONTEXTO Y GI',6,1,'Rol de la organización como responsable y/o encargado del tratamiento, partes interesadas con responsabilidades sobre datos personales y legislación aplicable (5.2.1–5.2.3).'),
  ('27701','Compromiso','PE1 PLANIFICACIÓN ESTRATÉGICA - S2 PE1 GESTIÓN DE RIESGOS','PE1 PLANIFICACIÓN ESTRATÉGICA','S2 PE1 GESTIÓN DE RIESGOS',10,2,'Riesgos para la privacidad integrados en el análisis de riesgos del SGSI; plan de tratamiento y declaración de aplicabilidad ampliada con los anexos A y B (5.4.1, 5.4.2).'),
  ('27701','Compromiso','PE1 PLANIFICACIÓN ESTRATÉGICA - S3 PE1 GESTIÓN DE EST, POLT Y OBJ','PE1 PLANIFICACIÓN ESTRATÉGICA','S3 PE1 GESTIÓN DE EST, POLT Y OBJ',8,3,'Política de privacidad, objetivos del SGIC y compromiso de la dirección; integración del SGIC en el SGSI (5.3, 5.4.2).'),
  ('27701','Compromiso','PE2 EVALUACIÓN DESEMPEÑO - S1 PE2 ANÁLISIS DE DATOS','PE2 EVALUACIÓN DESEMPEÑO','S1 PE2 ANÁLISIS DE DATOS',4,4,'Indicadores del SGIC: solicitudes de derechos y plazos de respuesta, brechas, evaluaciones de impacto realizadas (5.7.1).'),
  ('27701','Compromiso','PE2 EVALUACIÓN DESEMPEÑO - S2 PE2 AUDITORÍA INTERNA','PE2 EVALUACIÓN DESEMPEÑO','S2 PE2 AUDITORÍA INTERNA',14,5,'Auditoría interna del SGIC, incluidos los controles de los anexos A (responsable) y B (encargado) (5.7.2).'),
  ('27701','Compromiso','PE2 EVALUACIÓN DESEMPEÑO - S3 PE2 REVISIÓN POR LA DIRECCIÓN','PE2 EVALUACIÓN DESEMPEÑO','S3 PE2 REVISIÓN POR LA DIRECCIÓN',4,6,'Revisión por la dirección con las entradas de privacidad: derechos, brechas, autoridades de control, cambios legales (5.7.3).'),
  ('27701','Compromiso','PE3 MEJORA CONTINUA - S1 PE3 GESTIÓN DE NO CONFORMIDADES','PE3 MEJORA CONTINUA','S1 PE3 GESTIÓN DE NO CONFORMIDADES',4,7,'No conformidades y acciones correctivas del SGIC; mejora continua (5.8).'),
  ('27701','Compromiso','PA1 GESTIÓN DE PERSONAS - S1 PA1 GESTIÓN DE PUESTOS Y ROLES','PA1 GESTIÓN DE PERSONAS','S1 PA1 GESTIÓN DE PUESTOS Y ROLES',4,8,'Roles y responsabilidades de privacidad: delegado de protección de datos o responsable de privacidad, propietarios de cada tratamiento (6.3.1.1, 7.2.1).'),
  ('27701','Compromiso','PA1 GESTIÓN DE PERSONAS - S2 PA1 DESARROLLO PERSONAS','PA1 GESTIÓN DE PERSONAS','S2 PA1 DESARROLLO PERSONAS',10,9,'Competencia y concienciación del personal en protección de datos; formación específica por rol (5.5.2, 5.5.3, 6.4.2).'),
  ('27701','Compromiso','PA3 GESTIÓN DEL CONOCIMIENTO - S1 PA3 GESTIÓN INFORMAC. DOC.','PA3 GESTIÓN DEL CONOCIMIENTO','S1 PA3 GESTIÓN INFORMAC. DOC.',4,10,'Documentación del SGIC: procedimientos, registros y evidencias exigidas por la norma (5.5.5).'),
  ('27701','Compromiso','PA3 GESTIÓN DEL CONOCIMIENTO - S2 PA3 CONTROL LEGAL','PA3 GESTIÓN DEL CONOCIMIENTO','S2 PA3 CONTROL LEGAL',8,11,'Identificación y seguimiento de la legislación de protección de datos aplicable: RGPD, LOPDGDD, normativa sectorial y criterios de la AEPD (5.2.1, 7.2.2).'),
  ('27701','Compromiso','PA5 GESTIÓN DE SEGURIDAD - S1 PA5 GESTION SEGURIDAD OPERACIONAL','PA5 GESTIÓN DE SEGURIDAD','S1 PA5 GESTION SEGURIDAD OPERACIONAL',8,12,'Controles de ISO 27002 extendidos a los datos personales: clasificación, soportes, borrado seguro, registro y supervisión (6.5, 6.8, 6.9).'),
  ('27701','Compromiso','PA5 GESTIÓN DE SEGURIDAD - S2 PA5 GESTION SEGURIDAD LÓGICA','PA5 GESTIÓN DE SEGURIDAD','S2 PA5 GESTION SEGURIDAD LÓGICA',6,13,'Control de acceso a datos personales, cifrado, minimización y seudonimización, registros de acceso (6.6, 6.7, 6.10, 7.4).'),
  ('27701','Compromiso','PA6 GESTIÓN DE PARTES SUBCONTRATADAS - S1 PA6 HOMOLOGACIÓN PROVEEDORES','PA6 GESTIÓN DE PARTES SUBCONTRATADAS','S1 PA6 HOMOLOGACIÓN PROVEEDORES',6,14,'Encargados y subencargados del tratamiento: contratos, garantías y cláusulas de protección de datos (7.2.6, 8.2, 8.5.6–8.5.8).'),
  ('27701','Compromiso','PA6 GESTIÓN DE PARTES SUBCONTRATADAS - S2 PA6 EVALUACIÓN PROVEEDORES','PA6 GESTIÓN DE PARTES SUBCONTRATADAS','S2 PA6 EVALUACIÓN PROVEEDORES',4,15,'Supervisión de encargados y subencargados; evidencias de cumplimiento (8.5).'),
  ('27701','Compromiso','PA19 GESTIÓN DE LA PRIVACIDAD - S1 PA19 REGISTRO DE TRATAMIENTOS Y BASES DE LEGITIMACIÓN (7.2.2, 7.2.8)','PA19 GESTIÓN DE LA PRIVACIDAD','S1 PA19 REGISTRO DE TRATAMIENTOS Y BASES DE LEGITIMACIÓN (7.2.2, 7.2.8)',12,16,'Inventario de actividades de tratamiento: finalidad, base de legitimación, consentimiento, categorías de datos, plazos de conservación.'),
  ('27701','Compromiso','PA19 GESTIÓN DE LA PRIVACIDAD - S2 PA19 EVALUACIONES DE IMPACTO Y PRIVACIDAD DESDE EL DISEÑO (7.2.5, 7.4)','PA19 GESTIÓN DE LA PRIVACIDAD','S2 PA19 EVALUACIONES DE IMPACTO Y PRIVACIDAD DESDE EL DISEÑO (7.2.5, 7.4)',10,17,'Metodología y realización de evaluaciones de impacto (EIPD); privacidad desde el diseño y por defecto en nuevos tratamientos y sistemas.'),
  ('27701','Compromiso','PA19 GESTIÓN DE LA PRIVACIDAD - S3 PA19 INFORMACIÓN Y DERECHOS DE LOS INTERESADOS (7.3)','PA19 GESTIÓN DE LA PRIVACIDAD','S3 PA19 INFORMACIÓN Y DERECHOS DE LOS INTERESADOS (7.3)',10,18,'Cláusulas informativas y procedimiento de atención de derechos: acceso, rectificación, supresión, portabilidad, oposición y limitación, con sus plazos.'),
  ('27701','Compromiso','PA19 GESTIÓN DE LA PRIVACIDAD - S4 PA19 GESTIÓN DE BRECHAS DE DATOS PERSONALES (6.13.1)','PA19 GESTIÓN DE LA PRIVACIDAD','S4 PA19 GESTIÓN DE BRECHAS DE DATOS PERSONALES (6.13.1)',10,19,'Detección, registro y evaluación de brechas; notificación a la autoridad de control en 72 horas y comunicación a los interesados cuando proceda.'),
  ('27701','Compromiso','PA19 GESTIÓN DE LA PRIVACIDAD - S5 PA19 TRANSFERENCIAS Y COMUNICACIÓN A TERCEROS (7.5, 8.5)','PA19 GESTIÓN DE LA PRIVACIDAD','S5 PA19 TRANSFERENCIAS Y COMUNICACIÓN A TERCEROS (7.5, 8.5)',6,20,'Transferencias internacionales y comunicaciones de datos: garantías, cláusulas contractuales tipo, registro de destinatarios.'),
  ('27701','Implantación','PE1 PLANIFICACIÓN ESTRATÉGICA - S1 PE1 GESTIÓN DEL CONTEXTO Y GI','PE1 PLANIFICACIÓN ESTRATÉGICA','S1 PE1 GESTIÓN DEL CONTEXTO Y GI',1.8,1,'Rol de la organización como responsable y/o encargado del tratamiento, partes interesadas con responsabilidades sobre datos personales y legislación aplicable (5.2.1–5.2.3).'),
  ('27701','Implantación','PE1 PLANIFICACIÓN ESTRATÉGICA - S2 PE1 GESTIÓN DE RIESGOS','PE1 PLANIFICACIÓN ESTRATÉGICA','S2 PE1 GESTIÓN DE RIESGOS',4.8,2,'Riesgos para la privacidad integrados en el análisis de riesgos del SGSI; plan de tratamiento y declaración de aplicabilidad ampliada con los anexos A y B (5.4.1, 5.4.2).'),
  ('27701','Implantación','PE1 PLANIFICACIÓN ESTRATÉGICA - S3 PE1 GESTIÓN DE EST, POLT Y OBJ','PE1 PLANIFICACIÓN ESTRATÉGICA','S3 PE1 GESTIÓN DE EST, POLT Y OBJ',3.6,3,'Política de privacidad, objetivos del SGIC y compromiso de la dirección; integración del SGIC en el SGSI (5.3, 5.4.2).'),
  ('27701','Implantación','PE2 EVALUACIÓN DESEMPEÑO - S1 PE2 ANÁLISIS DE DATOS','PE2 EVALUACIÓN DESEMPEÑO','S1 PE2 ANÁLISIS DE DATOS',2.4,4,'Indicadores del SGIC: solicitudes de derechos y plazos de respuesta, brechas, evaluaciones de impacto realizadas (5.7.1).'),
  ('27701','Implantación','PE2 EVALUACIÓN DESEMPEÑO - S2 PE2 AUDITORÍA INTERNA','PE2 EVALUACIÓN DESEMPEÑO','S2 PE2 AUDITORÍA INTERNA',3.6,5,'Auditoría interna del SGIC, incluidos los controles de los anexos A (responsable) y B (encargado) (5.7.2).'),
  ('27701','Implantación','PE2 EVALUACIÓN DESEMPEÑO - S3 PE2 REVISIÓN POR LA DIRECCIÓN','PE2 EVALUACIÓN DESEMPEÑO','S3 PE2 REVISIÓN POR LA DIRECCIÓN',1.8,6,'Revisión por la dirección con las entradas de privacidad: derechos, brechas, autoridades de control, cambios legales (5.7.3).'),
  ('27701','Implantación','PE3 MEJORA CONTINUA - S1 PE3 GESTIÓN DE NO CONFORMIDADES','PE3 MEJORA CONTINUA','S1 PE3 GESTIÓN DE NO CONFORMIDADES',1.8,7,'No conformidades y acciones correctivas del SGIC; mejora continua (5.8).'),
  ('27701','Implantación','PA1 GESTIÓN DE PERSONAS - S1 PA1 GESTIÓN DE PUESTOS Y ROLES','PA1 GESTIÓN DE PERSONAS','S1 PA1 GESTIÓN DE PUESTOS Y ROLES',2.4,8,'Roles y responsabilidades de privacidad: delegado de protección de datos o responsable de privacidad, propietarios de cada tratamiento (6.3.1.1, 7.2.1).'),
  ('27701','Implantación','PA1 GESTIÓN DE PERSONAS - S2 PA1 DESARROLLO PERSONAS','PA1 GESTIÓN DE PERSONAS','S2 PA1 DESARROLLO PERSONAS',2.4,9,'Competencia y concienciación del personal en protección de datos; formación específica por rol (5.5.2, 5.5.3, 6.4.2).'),
  ('27701','Implantación','PA3 GESTIÓN DEL CONOCIMIENTO - S1 PA3 GESTIÓN INFORMAC. DOC.','PA3 GESTIÓN DEL CONOCIMIENTO','S1 PA3 GESTIÓN INFORMAC. DOC.',2.4,10,'Documentación del SGIC: procedimientos, registros y evidencias exigidas por la norma (5.5.5).'),
  ('27701','Implantación','PA3 GESTIÓN DEL CONOCIMIENTO - S2 PA3 CONTROL LEGAL','PA3 GESTIÓN DEL CONOCIMIENTO','S2 PA3 CONTROL LEGAL',2.4,11,'Identificación y seguimiento de la legislación de protección de datos aplicable: RGPD, LOPDGDD, normativa sectorial y criterios de la AEPD (5.2.1, 7.2.2).'),
  ('27701','Implantación','PA5 GESTIÓN DE SEGURIDAD - S1 PA5 GESTION SEGURIDAD OPERACIONAL','PA5 GESTIÓN DE SEGURIDAD','S1 PA5 GESTION SEGURIDAD OPERACIONAL',3.0,12,'Controles de ISO 27002 extendidos a los datos personales: clasificación, soportes, borrado seguro, registro y supervisión (6.5, 6.8, 6.9).'),
  ('27701','Implantación','PA5 GESTIÓN DE SEGURIDAD - S2 PA5 GESTION SEGURIDAD LÓGICA','PA5 GESTIÓN DE SEGURIDAD','S2 PA5 GESTION SEGURIDAD LÓGICA',3.0,13,'Control de acceso a datos personales, cifrado, minimización y seudonimización, registros de acceso (6.6, 6.7, 6.10, 7.4).'),
  ('27701','Implantación','PA6 GESTIÓN DE PARTES SUBCONTRATADAS - S1 PA6 HOMOLOGACIÓN PROVEEDORES','PA6 GESTIÓN DE PARTES SUBCONTRATADAS','S1 PA6 HOMOLOGACIÓN PROVEEDORES',1.8,14,'Encargados y subencargados del tratamiento: contratos, garantías y cláusulas de protección de datos (7.2.6, 8.2, 8.5.6–8.5.8).'),
  ('27701','Implantación','PA6 GESTIÓN DE PARTES SUBCONTRATADAS - S2 PA6 EVALUACIÓN PROVEEDORES','PA6 GESTIÓN DE PARTES SUBCONTRATADAS','S2 PA6 EVALUACIÓN PROVEEDORES',1.2,15,'Supervisión de encargados y subencargados; evidencias de cumplimiento (8.5).'),
  ('27701','Implantación','PA19 GESTIÓN DE LA PRIVACIDAD - S1 PA19 REGISTRO DE TRATAMIENTOS Y BASES DE LEGITIMACIÓN (7.2.2, 7.2.8)','PA19 GESTIÓN DE LA PRIVACIDAD','S1 PA19 REGISTRO DE TRATAMIENTOS Y BASES DE LEGITIMACIÓN (7.2.2, 7.2.8)',4.8,16,'Inventario de actividades de tratamiento: finalidad, base de legitimación, consentimiento, categorías de datos, plazos de conservación.'),
  ('27701','Implantación','PA19 GESTIÓN DE LA PRIVACIDAD - S2 PA19 EVALUACIONES DE IMPACTO Y PRIVACIDAD DESDE EL DISEÑO (7.2.5, 7.4)','PA19 GESTIÓN DE LA PRIVACIDAD','S2 PA19 EVALUACIONES DE IMPACTO Y PRIVACIDAD DESDE EL DISEÑO (7.2.5, 7.4)',3.6,17,'Metodología y realización de evaluaciones de impacto (EIPD); privacidad desde el diseño y por defecto en nuevos tratamientos y sistemas.'),
  ('27701','Implantación','PA19 GESTIÓN DE LA PRIVACIDAD - S3 PA19 INFORMACIÓN Y DERECHOS DE LOS INTERESADOS (7.3)','PA19 GESTIÓN DE LA PRIVACIDAD','S3 PA19 INFORMACIÓN Y DERECHOS DE LOS INTERESADOS (7.3)',3.6,18,'Cláusulas informativas y procedimiento de atención de derechos: acceso, rectificación, supresión, portabilidad, oposición y limitación, con sus plazos.'),
  ('27701','Implantación','PA19 GESTIÓN DE LA PRIVACIDAD - S4 PA19 GESTIÓN DE BRECHAS DE DATOS PERSONALES (6.13.1)','PA19 GESTIÓN DE LA PRIVACIDAD','S4 PA19 GESTIÓN DE BRECHAS DE DATOS PERSONALES (6.13.1)',3.0,19,'Detección, registro y evaluación de brechas; notificación a la autoridad de control en 72 horas y comunicación a los interesados cuando proceda.'),
  ('27701','Implantación','PA19 GESTIÓN DE LA PRIVACIDAD - S5 PA19 TRANSFERENCIAS Y COMUNICACIÓN A TERCEROS (7.5, 8.5)','PA19 GESTIÓN DE LA PRIVACIDAD','S5 PA19 TRANSFERENCIAS Y COMUNICACIÓN A TERCEROS (7.5, 8.5)',1.8,20,'Transferencias internacionales y comunicaciones de datos: garantías, cláusulas contractuales tipo, registro de destinatarios.');

-- ── Abreviatura en el código de proyecto ───────────────────────────────────
create or replace function public.codigo_proyecto(p_cliente text, p_anio integer, p_modelo text, p_normas text[])
returns text language plpgsql immutable as $$
declare serv text; ns text[] := '{}'; n text; corta text;
begin
  serv := case p_modelo
    when 'Implantación' then 'IMP' when 'Apoyo' then 'APO'
    when 'Relación' then 'REL' when 'Implicación' then 'IML'
    when 'Compromiso' then 'CMP' else 'XXX' end;

  foreach n in array coalesce(p_normas, '{}') loop
    corta := case n
      when '9001' then '9'   when '14001' then '14' when '27001' then '27'
      when '27701' then '277'
      when '45001' then '45' when '42001' then '42' when '56001' then '56'
      when '21001' then '21' when '9004' then '9004'
      when '93200' then '932' when '158101' then '158' when '66181' then '661'
      when 'igualdad' then 'IG'  when 'igualdad-seg' then 'IGS'
      when 'diversidad' then 'DV' when 'diversidad-seg' then 'DVS'
      when 'madridexcelente' then 'ME'
      else upper(substr(n, 1, 3)) end;
    ns := ns || corta;
  end loop;

  return public.sigla_cliente(p_cliente) || '-' || coalesce(p_anio, extract(year from current_date)::int)::text
       || '-' || serv || case when array_length(ns,1) > 0 then '-' || array_to_string(ns, '-') else '' end;
end $$;

notify pgrst, 'reload schema';

-- ── Comprobación ───────────────────────────────────────────────────────────
select 'v117 aplicada' as ok;
select modelo, count(*) as tareas, sum(horas_base) as horas
  from public.tareas_catalogo where norma_id = '27701' group by modelo order by modelo;   -- 5 filas × 20 tareas
select public.codigo_proyecto('Empresa Ejemplo', 2026, 'Relación', array['27001','27701']) as codigo;  -- EMEJ-2026-REL-27-277
