-- =============================================================================
-- CONSULTIFY · Migración v45 · Blog público (publicación automática por fecha)
-- -----------------------------------------------------------------------------
-- Tabla blog_posts. La publicación automática se logra con la política RLS de
-- SELECT: un post solo es visible cuando su fecha_publicacion <= hoy y no es
-- borrador. Así, sin cron ni funciones, el post del día 13 aparece el día 13.
-- =============================================================================

begin;

create table if not exists public.blog_posts (
  id                bigint generated by default as identity primary key,
  slug              text unique not null,
  titulo            text,
  extracto          text,
  contenido_html    text,
  cta               text,
  pilar             text,
  autor             text default 'TuConsultor',
  fecha_publicacion date not null,
  estado            text default 'programado',
  tags              text[],
  creado_en         timestamptz default now()
);

create index if not exists idx_blog_posts_fecha on public.blog_posts (fecha_publicacion desc);
create index if not exists idx_blog_posts_slug on public.blog_posts (slug);

-- ── RLS: solo posts ya publicados (fecha <= hoy) y no borradores ────────────
alter table public.blog_posts enable row level security;

-- La política NO consulta auth.users (esquema protegido). Solo compara fechas
-- y estado, así que vale igual para anónimos y autenticados.
drop policy if exists blog_posts_select_publicos on public.blog_posts;
create policy blog_posts_select_publicos on public.blog_posts
  for select
  to anon, authenticated
  using (fecha_publicacion <= current_date and estado <> 'borrador');

-- Grants explícitos de lectura.
grant select on public.blog_posts to anon, authenticated;

commit;

-- Recargar cache de PostgREST.
notify pgrst, 'reload schema';
select pg_notify('pgrst', 'reload schema');
