-- =============================================================================
-- CONSULTIFY · SEED · Blog posts 2026 (36 artículos)
-- Ejecutar DESPUÉS de la migración v45. Idempotente por slug (on conflict).
-- Textos y fechas SIN modificar respecto al JSON original.
-- =============================================================================

begin;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('errores-auditoria-interna-iso-9001', '5 errores que hacen suspender una auditoría interna ISO 9001', 'El 80% de las no conformidades que vemos se repiten. Estas son las cinco de siempre.', '<p>El 80% de las no conformidades que encontramos en auditorías internas se repiten empresa tras empresa. No son fallos exóticos: son los cinco de siempre.</p><ul><li><strong>1. Auditar con la norma en la mano y sin leer los procesos.</strong> La auditoría interna evalúa TU sistema, no la norma en abstracto.</li><li><strong>2. Objetivos sin seguimiento.</strong> Se definen en enero y nadie los vuelve a mirar hasta diciembre.</li><li><strong>3. Acciones correctivas sin análisis de causa.</strong> Corregir el síntoma no cierra la no conformidad, la aplaza.</li><li><strong>4. Registros de formación incompletos.</strong> La competencia hay que poder demostrarla, no solo afirmarla.</li><li><strong>5. Revisión por la dirección de trámite.</strong> Un acta copiada del año anterior se detecta en dos minutos.</li></ul><p>La buena noticia: los cinco se resuelven con método, no con más papeleo.</p>', '¿Quieres que revisemos tu sistema antes de la próxima auditoría? Escríbenos a hola@tuconsultor.com.', 'P5 CONSEJOS', 'TuConsultor', '2026-07-13', 'programado', '{"consejos"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('iso-42001-explicada', 'ISO 42001 explicada en 2 minutos: la norma de gestión de IA', 'Tu empresa ya usa IA. ¿Tienes un sistema para gestionarla?', '<p>Tu empresa ya usa inteligencia artificial, aunque no lo hayas formalizado: redacción de textos, análisis de datos, atención al cliente. La pregunta es si la usas con control o con suerte.</p><p>La <strong>ISO/IEC 42001</strong> es la primera norma internacional certificable de sistemas de gestión de IA. Funciona igual que la 9001 que ya conoces: contexto, riesgos, objetivos, controles operativos, auditoría y mejora, pero aplicado al ciclo de vida de los sistemas de IA.</p><p>¿Qué aporta en la práctica?</p><ul><li>Un inventario de dónde y cómo se usa IA en la organización.</li><li>Evaluación de impactos: sesgos, privacidad, transparencia, seguridad.</li><li>Roles y responsabilidades claros cuando la IA toma o apoya decisiones.</li><li>Confianza demostrable ante clientes y administración.</li></ul><p>Si ya tienes 9001 o 27001, el 60% del camino está andado: la estructura de alto nivel es la misma.</p>', '¿Usáis IA en procesos y queréis ordenarla? Hablemos: hola@tuconsultor.com.', 'P1 EDUCATIVO', 'TuConsultor', '2026-07-15', 'programado', '{"educativo"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('pyme-industrial-certificacion-6-meses', 'Cómo una pyme industrial pasó su primera certificación ISO 9001 en 6 meses', 'Llegaron sin un solo procedimiento escrito. Seis meses después: certificado sin no conformidades mayores.', '<p>Cuando empezamos a trabajar con esta pyme industrial madrileña no tenían un solo procedimiento escrito. Tenían algo mejor: procesos reales que funcionaban en la cabeza de su gente. Nuestro trabajo no fue inventar un sistema, fue escribir el que ya existía y reforzar lo que cojeaba.</p><p>El plan en 6 meses:</p><ul><li><strong>Mes 1-2:</strong> diagnóstico, mapa de procesos y análisis de contexto. Solo lo imprescindible.</li><li><strong>Mes 3-4:</strong> documentación ligera (una página por proceso donde fue posible) y formación al equipo.</li><li><strong>Mes 5:</strong> auditoría interna y revisión por la dirección con datos reales.</li><li><strong>Mes 6:</strong> auditoría de certificación. Resultado: cero no conformidades mayores.</li></ul><p>La clave no fue correr: fue no fabricar burocracia que luego nadie mantiene.</p>', '¿Tu empresa necesita certificarse sin ahogarse en papeles? Cuéntanos tu caso.', 'P2 CASOS', 'TuConsultor', '2026-07-16', 'programado', '{"casos"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('checklist-revision-por-la-direccion', 'Checklist: qué preparar antes de la revisión por la dirección', 'La revisión por la dirección no es una reunión más. Es LA reunión.', '<p>La revisión por la dirección no es una reunión más: es el momento en que el sistema de gestión y la estrategia de la empresa se miran a la cara. Esto es lo que debe estar sobre la mesa antes de empezar:</p><ul><li>Estado de las acciones de la revisión anterior (todas, no solo las cerradas).</li><li>Cambios en el contexto: mercado, legislación, clientes, riesgos nuevos.</li><li>Resultados de indicadores y grado de cumplimiento de objetivos.</li><li>Satisfacción del cliente y reclamaciones, con datos, no impresiones.</li><li>Resultados de auditorías internas y externas.</li><li>No conformidades y estado de las acciones correctivas.</li><li>Desempeño de proveedores externos.</li><li>Adecuación de recursos: ¿falta gente, formación, herramientas?</li></ul><p>Y la salida más importante: <strong>decisiones</strong>. Una revisión sin decisiones es un acta, no una revisión.</p>', 'Guarda esta lista para tu próxima revisión. ¿Dudas? hola@tuconsultor.com.', 'P5 CONSEJOS', 'TuConsultor', '2026-07-20', 'programado', '{"consejos"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('ia-consultor-calidad', 'La IA no va a sustituir al consultor de calidad. Va a sustituir al que no la use', 'Llevo 20 años en consultoría ISO. Esto es lo que está cambiando de verdad.', '<p>Llevo 20 años en consultoría de sistemas de gestión y nunca había visto un cambio tan rápido como el de los últimos dos años.</p><p>La IA ya redacta borradores de procedimientos, analiza indicadores y prepara auditorías. Lo hace en minutos. ¿Significa eso el fin del consultor? No: significa el fin del consultor que solo aportaba eso.</p><p>Lo que la IA no hace (todavía) es lo que siempre fue el valor real del oficio: entender el negocio del cliente, detectar lo que no está escrito, negociar con una dirección escéptica, y distinguir entre un sistema que funciona y uno que solo parece que funciona.</p><p>En TuConsultor hemos construido nuestra propia plataforma, <strong>Consultify</strong>, precisamente para automatizar lo automatizable y dedicar las horas de consultor a lo que de verdad las necesita.</p><p>La herramienta cambia. El criterio, no.</p>', '¿Cómo lo ves tú? Nos encantará leer tu opinión.', 'P3 OPINIÓN', 'TuConsultor', '2026-07-22', 'programado', '{"opinion"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('quienes-somos-tuconsultor', 'Desde 2006 gestionando con el corazón: quiénes somos', 'Detrás de cada certificado hay un equipo. Este es el nuestro.', '<p>Detrás de cada certificado que ayudamos a conseguir hay un equipo que lleva desde 2006 haciendo lo mismo con la misma ilusión: ayudar a pymes a gestionar mejor.</p><p>Somos <strong>TuConsultor</strong>, consultora madrileña especializada en sistemas de gestión: ISO 9001, 14001, 45001, 27001, 42001, EFQM y más. Trabajamos con cinco modelos de colaboración distintos, desde el apoyo puntual hasta la implantación completa, porque no todas las empresas necesitan lo mismo.</p><p>En 2026 dimos un paso más y construimos <strong>Consultify</strong>, nuestra propia plataforma de gestión de proyectos de consultoría, porque ninguna herramienta del mercado encajaba con nuestra forma de trabajar.</p><p>Lo que no ha cambiado en veinte años: hablamos claro, contamos también lo que no funciona y medimos nuestro éxito por las auditorías que superan nuestros clientes, no por las horas que facturamos.</p>', 'Conócenos en tuconsultor.com o escríbenos a hola@tuconsultor.com.', 'P4 MARCA', 'TuConsultor', '2026-07-23', 'programado', '{"marca"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('7-indicadores-sistema-gestion', '7 indicadores que todo sistema de gestión debería medir (y casi nadie mide)', 'Medir por medir no sirve. Estos 7 KPI sí mueven la aguja.', '<p>Medir por medir no sirve de nada. La mayoría de cuadros de indicadores que vemos están llenos de métricas que nadie usa para decidir. Estos siete sí mueven la aguja:</p><ul><li><strong>Coste de la no calidad:</strong> reprocesos, devoluciones, garantías. El indicador que más duele y más motiva.</li><li><strong>Tiempo de cierre de no conformidades:</strong> mide la salud real de tu mejora continua.</li><li><strong>% de acciones correctivas eficaces</strong> (que no reaparecen en 12 meses).</li><li><strong>Tasa de reclamaciones por pedido/proyecto</strong>, no en valor absoluto.</li><li><strong>Cumplimiento de plazos de entrega</strong>, medido contra la fecha comprometida original.</li><li><strong>Rotación y absentismo:</strong> el sistema también gestiona personas.</li><li><strong>% de objetivos con seguimiento al día:</strong> el meta-indicador que delata sistemas abandonados.</li></ul><p>Regla de oro: si un indicador lleva dos revisiones sin provocar ninguna decisión, elimínalo o cámbialo.</p>', '¿Cuál añadirías tú? Escríbenos y lo debatimos.', 'P5 CONSEJOS', 'TuConsultor', '2026-07-27', 'programado', '{"consejos"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('iso-9001-vs-efqm', 'ISO 9001 vs EFQM: ¿cuál necesita tu empresa?', 'No son competidoras. Son etapas distintas del mismo camino.', '<p>Nos lo preguntan constantemente: ¿ISO 9001 o EFQM? La respuesta corta: no son competidoras, son etapas distintas del mismo camino.</p><p><strong>ISO 9001</strong> es una norma certificable de requisitos mínimos: define lo que un sistema de gestión de calidad debe tener. Es binaria: cumples o no cumples. Es la puerta de entrada y, en muchos sectores, un requisito comercial.</p><p><strong>EFQM</strong> es un modelo de excelencia: no certifica mínimos, evalúa madurez. Con la lógica RADAR puntúa de 0 a 1000 cómo de bien diriges, ejecutas y obtienes resultados. Sirve para saber dónde estás y hacia dónde mejorar, incluso si ya llevas años certificado.</p><p>Nuestra recomendación habitual: 9001 primero para ordenar la casa; EFQM cuando el sistema ya rueda y quieres pasar de "cumplir" a "destacar". El modelo EFQM 2025, además, pone el foco en transformación, sostenibilidad y datos: muy alineado con lo que las pymes necesitan ahora.</p>', '¿Quieres saber en qué punto está tu organización? Hacemos diagnósticos EFQM.', 'P1 EDUCATIVO', 'TuConsultor', '2026-07-29', 'programado', '{"educativo"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('de-47-no-conformidades-a-3', 'De 47 no conformidades a 3: un año de mejora continua real', 'Heredamos un sistema con 47 no conformidades abiertas. Así lo ordenamos.', '<p>Cuando este cliente llegó a nosotros, su sistema arrastraba <strong>47 no conformidades abiertas</strong>, algunas con más de dos años de antigüedad. El sistema no estaba roto: estaba atascado.</p><p>Lo que hicimos, por orden:</p><ul><li><strong>Triaje honesto.</strong> De las 47, doce eran duplicadas o ya resueltas sin registrar. Quedaron 35 reales.</li><li><strong>Análisis de causa en serio.</strong> Agrupadas por causa raíz, las 35 se redujeron a 9 problemas de fondo. Casi todos apuntaban a dos procesos.</li><li><strong>Un responsable y una fecha por acción.</strong> Nada de "el departamento". Un nombre.</li><li><strong>Seguimiento quincenal de 20 minutos.</strong> Corto, incómodo y eficaz.</li></ul><p>Doce meses después: 3 no conformidades abiertas, todas del último trimestre y en plazo. La auditoría de seguimiento lo destacó como punto fuerte.</p><p>La mejora continua no es una cláusula. Es una rutina.</p>', '¿Tu sistema acumula no conformidades? Podemos ayudarte a desatascarlo.', 'P2 CASOS', 'TuConsultor', '2026-07-30', 'programado', '{"casos"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('gestion-riesgos-iso-util', 'Gestión de riesgos ISO: cómo hacerla útil y no un Excel muerto', 'Tu matriz de riesgos no debería actualizarse solo la semana antes de la auditoría.', '<p>Confesión de auditor: sabemos perfectamente cuándo una matriz de riesgos se actualizó la semana antes de la auditoría. Se nota. Para que la gestión de riesgos sirva de algo:</p><ul><li><strong>Menos riesgos, mejor pensados.</strong> Diez riesgos relevantes valen más que cincuenta genéricos copiados de una plantilla.</li><li><strong>Vincula cada riesgo a un proceso y a un dueño.</strong> Un riesgo sin responsable es un párrafo, no un riesgo.</li><li><strong>Acciones con fecha, no "controles" eternos.</strong> Si la acción de mitigación lleva tres años "en curso", no existe.</li><li><strong>Revísala cuando pase algo, no por calendario.</strong> Un cliente nuevo grande, una norma nueva, un incidente: eso dispara la revisión.</li><li><strong>Úsala en la revisión por la dirección.</strong> Si los riesgos no aparecen cuando se toman decisiones, el Excel está muerto.</li></ul><p>El objetivo no es tener una matriz bonita. Es que ningún problema previsible te pille por sorpresa.</p>', 'Guarda este método y aplícalo en tu próxima revisión de riesgos.', 'P5 CONSEJOS', 'TuConsultor', '2026-08-03', 'programado', '{"consejos"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('mayor-freno-para-certificarse', '¿Cuál es el mayor freno para certificarse? Preguntamos a gerentes de pyme', 'Pregunta honesta a gerentes de pyme: ¿qué os frena de verdad?', '<p>Llevamos meses haciendo la misma pregunta a gerentes de pymes que aún no se han certificado: <strong>¿qué os frena de verdad?</strong> Las respuestas se repiten:</p><ul><li><strong>"El papeleo"</strong> — el miedo a que la ISO burocratice la empresa. Es el freno número uno y el mito más extendido.</li><li><strong>"El coste"</strong> — consultoría más certificadora más horas internas. Legítimo, aunque casi nadie calcula el coste de NO tener sistema.</li><li><strong>"No tenemos tiempo"</strong> — que suele significar "no tenemos a nadie que lo lidere".</li><li><strong>"No sabemos por dónde empezar"</strong> — el más fácil de resolver y el que más parálisis genera.</li></ul><p>Nuestra lectura honesta: los cuatro frenos son reales, pero los cuatro se resuelven con el mismo antídoto: un sistema diseñado a la medida de la empresa, no una plantilla genérica de 200 páginas.</p><p>¿Cuál es tu freno? Nos interesa de verdad la respuesta.</p>', 'Cuéntanos qué te frena: hola@tuconsultor.com. Sin compromiso y sin argumentario de venta.', 'P3 OPINIÓN', 'TuConsultor', '2026-08-05', 'programado', '{"opinion"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('consultify-9-normas-5-modelos', 'Así gestionamos 9 normas y 5 modelos de consultoría con Consultify', 'Construimos nuestra propia plataforma porque ninguna herramienta encajaba. Esto es Consultify.', '<p>Durante años gestionamos nuestros proyectos de consultoría con hojas de cálculo, carpetas compartidas y memoria. Funcionaba, hasta que dejó de funcionar: 9 normas distintas, 5 modelos de servicio, decenas de clientes simultáneos y un equipo creciendo.</p><p>Ninguna herramienta del mercado encajaba con la forma de trabajar de una consultora ISO. Así que construimos la nuestra: <strong>Consultify</strong>.</p><p>Qué hace por nosotros cada día:</p><ul><li>Planifica proyectos por norma, modelo y consultor, con horas previstas y efectivas.</li><li>Controla la facturación y el estado de cobros con un semáforo conectado a nuestra contabilidad.</li><li>Mantiene el catálogo de tareas por proceso y subproceso para las 9 normas que trabajamos.</li><li>Sincroniza clientes con nuestras herramientas de comunicación automáticamente.</li></ul><p>Lo construimos para nosotros, pensando en cómo trabaja una consultora de verdad. Y se nota.</p>', '¿Quieres verla por dentro? Pide una demo en consultify.pro.', 'P4 MARCA', 'TuConsultor', '2026-08-06', 'programado', '{"marca"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('como-redactar-no-conformidad', 'Cómo redactar una no conformidad que de verdad sirva para mejorar', '"Falta de compromiso" no es una no conformidad. Es una excusa mal escrita.', '<p>"Falta de compromiso del personal" no es una no conformidad: es una excusa mal escrita. Una no conformidad útil tiene tres partes, siempre:</p><ul><li><strong>Evidencia:</strong> el hecho objetivo y verificable. "En el pedido 2026-0341 no consta el registro de inspección final."</li><li><strong>Requisito incumplido:</strong> qué punto de la norma o de tu propio procedimiento se incumple. "El procedimiento PC-05 exige inspección final documentada."</li><li><strong>Naturaleza del incumplimiento:</strong> la conexión entre ambas, sin juicios de valor ni culpables.</li></ul><p>Lo que nunca debe llevar: nombres propios, adjetivos ("grave", "inaceptable"), causas presupuestas ("por falta de formación") ni soluciones ("se debería..."). La causa se investiga después; la solución la decide el dueño del proceso.</p><p>Una no conformidad bien redactada se cierra sola en la mitad de tiempo, porque nadie discute hechos.</p>', 'Guarda esta estructura y úsala en tu próxima auditoría interna.', 'P5 CONSEJOS', 'TuConsultor', '2026-08-10', 'programado', '{"consejos"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('iso-27001-ens-administracion', 'ISO 27001 + ENS: lo que toda empresa que trabaja con la administración debe saber', 'Si facturas a la administración pública, el ENS ya no es opcional.', '<p>Si tu empresa presta servicios a la administración pública española que impliquen tratar su información o sus sistemas, el <strong>Esquema Nacional de Seguridad (ENS)</strong> no es opcional: es un requisito legal, y cada vez más pliegos lo exigen certificado.</p><p>¿Y la ISO 27001? Es la norma internacional de seguridad de la información, certificable y reconocida mundialmente. Se solapan mucho, pero no son lo mismo:</p><ul><li>El <strong>ENS</strong> es obligatorio para el sector público y sus proveedores, con categorías Básica, Media y Alta según el sistema.</li><li>La <strong>27001</strong> es voluntaria, comercialmente muy valorada, y estructura la seguridad como sistema de gestión.</li></ul><p>La buena noticia: si haces bien una, la otra está al 70%. El análisis de riesgos, los controles y la documentación se comparten en gran medida. Nuestra recomendación para proveedores de la administración: abordarlas juntas y en un solo proyecto. Se ahorra tiempo, dinero y esquizofrenia documental.</p>', '¿Te piden ENS en un pliego y no sabes por dónde empezar? Escríbenos.', 'P1 EDUCATIVO', 'TuConsultor', '2026-08-12', 'programado', '{"educativo"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('integrar-9001-14001-45001', 'Integrar ISO 9001 + 14001 + 45001: menos papeles, un solo sistema', 'Tres normas no significan tres sistemas. Significan uno bien hecho.', '<p>Este cliente llegó con tres sistemas paralelos: uno de calidad, uno de medio ambiente y uno de seguridad y salud. Tres manuales, tres juegos de procedimientos, tres auditorías internas y un equipo agotado de mantener triplicado lo que era lo mismo.</p><p>Las tres normas comparten estructura (la llamada estructura de alto nivel): contexto, liderazgo, planificación, soporte, operación, evaluación y mejora. Lo que hicimos fue, sencillamente, tomárnoslo en serio:</p><ul><li>Un único análisis de contexto y partes interesadas con las tres perspectivas.</li><li>Una sola matriz de riesgos con columnas de calidad, ambiente y seguridad.</li><li>Procedimientos integrados: un solo control documental, una sola gestión de no conformidades.</li><li>Una auditoría interna integrada y una única revisión por la dirección.</li></ul><p>Resultado: la documentación se redujo un 40% y la auditoría de certificación integrada costó menos que dos de las tres que hacían antes por separado.</p>', '¿Mantienes sistemas duplicados? Calculamos cuánto podrías simplificar.', 'P2 CASOS', 'TuConsultor', '2026-08-13', 'programado', '{"casos"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('5-documentos-auditor', 'Los 5 documentos que tu auditor va a pedir sí o sí', 'Da igual la norma: estos 5 documentos salen en todas las auditorías.', '<p>Da igual que sea 9001, 14001 o 27001: hay cinco documentos que el auditor va a pedir en los primeros treinta minutos. Tenerlos impecables marca el tono de toda la auditoría:</p><ul><li><strong>El análisis de contexto y partes interesadas.</strong> Actualizado este año, no el de la implantación.</li><li><strong>Los objetivos con su seguimiento.</strong> Con datos de verdad, no casillas de "en curso".</li><li><strong>El informe de la última auditoría interna</strong> y el estado de sus hallazgos.</li><li><strong>El acta de la revisión por la dirección</strong>, con decisiones reconocibles.</li><li><strong>El registro de no conformidades y acciones correctivas</strong> del periodo.</li></ul><p>¿Por qué estos cinco? Porque juntos cuentan la historia completa: si el sistema piensa (contexto), quiere (objetivos), se vigila (auditoría), decide (revisión) y aprende (acciones). Un sistema que tiene esto vivo, tiene casi todo lo demás bien.</p>', 'Guarda esta lista y revísala 90 días antes de tu próxima auditoría.', 'P5 CONSEJOS', 'TuConsultor', '2026-08-17', 'programado', '{"consejos"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('efqm-2025-que-cambia', 'EFQM 2025: qué cambia y por qué importa a las pymes', 'El nuevo modelo EFQM no es solo para grandes. Te explico por qué.', '<p>Existe la creencia de que el modelo EFQM es cosa de grandes corporaciones con departamentos de excelencia. El modelo 2025 desmonta esa idea, y creemos que las pymes deberían prestarle atención.</p><p>Lo esencial del EFQM 2025:</p><ul><li>Mantiene la estructura de <strong>7 criterios</strong> en tres bloques: Dirección, Ejecución y Resultados.</li><li>Refuerza el peso de la <strong>transformación</strong>: no evalúa solo cómo gestionas hoy, sino cómo te preparas para mañana.</li><li>Integra de lleno <strong>sostenibilidad y tecnología</strong> como ejes transversales, no como anexos.</li><li>La lógica <strong>RADAR</strong> sigue siendo el corazón: enfoques, despliegue, evaluación y revisión, con puntuación de 0 a 1000.</li></ul><p>¿Por qué le importa a una pyme? Porque una autoevaluación EFQM bien hecha es el diagnóstico estratégico más completo que existe por su coste: te dice exactamente dónde estás fuerte, dónde cojeas y qué priorizar, con un lenguaje que la dirección entiende.</p>', 'Hacemos autoevaluaciones EFQM 2025 con informe ejecutivo. Pregúntanos.', 'P3 OPINIÓN', 'TuConsultor', '2026-08-19', 'programado', '{"opinion"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('20-anos-lecciones', '20 años de consultoría: lo que aprendimos de nuestros errores', 'No siempre acertamos. Estas son 3 lecciones que nos costaron caras.', '<p>Veinte años de consultoría dan para muchos aciertos y para algunos errores que preferiríamos no haber cometido. Contamos tres, porque nos hicieron mejores:</p><ul><li><strong>Aceptar proyectos con la dirección desconectada.</strong> Al principio pensábamos que podíamos compensarlo con esfuerzo. No. Si la dirección no lidera, el sistema nace muerto. Hoy lo evaluamos antes de firmar.</li><li><strong>Documentar de más.</strong> En nuestros primeros años entregábamos manuales enciclopédicos. Aprendimos que cada página que el cliente no usa es una página que trabaja contra el sistema. Hoy nuestro estándar es: lo mínimo que funcione.</li><li><strong>Callar diagnósticos incómodos.</strong> Una vez suavizamos un informe para no incomodar. El problema estalló seis meses después, más caro. Desde entonces, la honestidad en el diagnóstico es innegociable, aunque duela.</li></ul><p>La experiencia no es acumular años: es acumular lecciones y cambiar por ellas.</p>', '¿Cuál ha sido tu mayor lección gestionando? Nos encantaría leerla.', 'P4 MARCA', 'TuConsultor', '2026-08-20', 'programado', '{"marca"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('plan-igualdad-checklist', 'Plan de Igualdad: checklist de obligaciones para empresas de más de 50 empleados', 'Si tienes más de 50 empleados y no tienes plan de igualdad, tienes un problema.', '<p>Si tu empresa tiene más de 50 personas en plantilla y no tiene plan de igualdad registrado, tiene un incumplimiento legal con sanciones que pueden superar los 7.500 euros, además de la exclusión de contratación pública. El checklist de mínimos:</p><ul><li><strong>Constituir la comisión negociadora</strong> con la representación legal de las personas trabajadoras.</li><li><strong>Diagnóstico de situación:</strong> datos de plantilla, retribuciones, promoción, formación y conciliación desagregados por sexo.</li><li><strong>Auditoría retributiva</strong> y registro salarial: obligatorios y con metodología concreta.</li><li><strong>Plan con objetivos, medidas, plazos e indicadores</strong> de seguimiento.</li><li><strong>Registro oficial (REGCON)</strong>: sin registro, el plan no existe legalmente.</li><li><strong>Seguimiento y evaluación periódica</strong>, no cajón y olvido.</li></ul><p>Vigencia máxima: 4 años. Si el tuyo se firmó en 2022, toca renovarlo ya.</p>', '¿Necesitas diagnóstico o renovación del plan? Te acompañamos en todo el proceso.', 'P5 CONSEJOS', 'TuConsultor', '2026-08-24', 'programado', '{"consejos"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('iso-56001-innovacion', 'ISO 56001: gestionar la innovación también se certifica', 'Innovar sin sistema es tener suerte. Innovar con sistema es tener método.', '<p>Muchas empresas innovan por chispazos: una idea del gerente, un cliente que pide algo nuevo, una urgencia que fuerza una solución. Funciona... hasta que deja de funcionar. Innovar sin sistema es tener suerte; innovar con sistema es tener método.</p><p>La <strong>ISO 56001</strong> es la norma certificable de sistemas de gestión de la innovación. No te dice qué innovar: te da la estructura para que la innovación no dependa del azar:</p><ul><li>Un proceso para captar oportunidades e ideas de forma sistemática.</li><li>Criterios para decidir en qué ideas invertir y cuáles descartar (esto es lo que casi nadie tiene).</li><li>Gestión de la incertidumbre: en innovación, fallar controladamente es parte del método.</li><li>Indicadores de innovación de verdad, más allá de "número de ideas del buzón".</li></ul><p>Además, un sistema de gestión de innovación certificado refuerza deducciones fiscales de I+D+i y puntúa en licitaciones y ayudas. Método que además sale rentable.</p>', '¿Tu empresa innova con método o con suerte? Hablemos de la 56001.', 'P1 EDUCATIVO', 'TuConsultor', '2026-08-26', 'programado', '{"educativo"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('auditoria-externa-a-la-primera', 'Auditoría externa superada a la primera: qué hizo diferente este cliente', 'No fue magia. Fueron 3 hábitos mantenidos durante 12 meses.', '<p>Este cliente superó su auditoría de certificación a la primera, sin no conformidades. No fue magia ni fue suerte: fueron tres hábitos mantenidos durante doce meses.</p><ul><li><strong>Quince minutos semanales de sistema.</strong> Cada lunes, la responsable de calidad revisaba tres cosas: no conformidades abiertas, indicadores fuera de rango y acciones pendientes. Quince minutos. Cincuenta y dos semanas.</li><li><strong>El sistema en las reuniones que ya existían.</strong> No crearon "reuniones de calidad": añadieron cinco minutos de sistema a la reunión de producción de los jueves. La calidad dejó de ser un mundo aparte.</li><li><strong>Registrar en el momento, no a final de mes.</strong> La regla era simple: lo que no se registra hoy, se inventa mañana. Y lo inventado se nota en auditoría.</li></ul><p>El auditor lo escribió textualmente en su informe: "sistema plenamente integrado en la operativa". Esa frase vale más que el certificado.</p>', '¿Quieres implantar estos hábitos en tu empresa? Es más fácil de lo que parece.', 'P2 CASOS', 'TuConsultor', '2026-08-27', 'programado', '{"casos"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('como-elegir-consultora-iso', 'Cómo elegir consultora ISO: 6 preguntas antes de firmar', 'No todas las consultoras trabajan igual. Estas preguntas separan el grano de la paja.', '<p>Sí, somos consultora y vamos a decirte cómo elegir consultora. Precisamente por eso: estas seis preguntas separan el grano de la paja, y no nos da miedo que nos las hagan.</p><ul><li><strong>¿Quién va a llevar mi proyecto exactamente?</strong> Nombre y experiencia. Que no te venda un senior y te envíe a un junior sin supervisión.</li><li><strong>¿La documentación será a medida o plantilla?</strong> Pide ver un ejemplo de un procedimiento real (anonimizado).</li><li><strong>¿Cuántas horas incluye y cómo se reparten?</strong> Desconfía de presupuestos sin desglose de dedicación.</li><li><strong>¿Qué pasa si la auditoría va mal?</strong> Una consultora seria te acompaña en el cierre de no conformidades sin coste extra abusivo.</li><li><strong>¿Me puedes dar referencias de mi sector?</strong> Y llámalas de verdad.</li><li><strong>¿Qué necesitas de mí?</strong> Si la respuesta es "casi nada", huye: un sistema sin implicación del cliente es un sistema de cartón.</li></ul>', 'Guárdalas para tu próxima reunión comercial. Con nosotros incluida.', 'P5 CONSEJOS', 'TuConsultor', '2026-08-31', 'programado', '{"consejos"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('precio-certificacion-barato-caro', 'El precio de una certificación: por qué lo barato sale caro', '"¿Cuánto cuesta el certificado?" es la pregunta equivocada. Te explico cuál es la correcta.', '<p>"¿Cuánto cuesta el certificado?" es la pregunta que más recibimos y es la pregunta equivocada. La correcta es: <strong>¿cuánto cuesta tener un sistema que funcione?</strong> El certificado es la consecuencia, no el producto.</p><p>Cuando un presupuesto de consultoría es sospechosamente barato, el ahorro sale de algún sitio: plantillas genéricas que no reflejan tu empresa, un consultor sin experiencia haciendo diez proyectos a la vez, o un sistema diseñado para engañar al auditor en lugar de servir al negocio.</p><p>Y ese ahorro se paga después: horas internas corrigiendo documentación inútil, no conformidades en auditoría, y lo peor, un sistema que la plantilla percibe como teatro y que muere en dos años.</p><p>Nuestra posición es transparente: trabajamos con tarifas por perfil de consultor y horas planificadas por proceso, con desglose completo en la oferta. Se puede comparar. Y eso es exactamente lo que recomendamos hacer.</p>', 'Pide presupuesto desglosado, a nosotros y a quien quieras. Luego compara.', 'P3 OPINIÓN', 'TuConsultor', '2026-09-02', 'programado', '{"opinion"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('un-dia-con-nuestras-consultoras', 'Un día con nuestras consultoras: cómo es un proyecto por dentro', 'Spoiler: hay menos papeleo y más conversaciones de las que imaginas.', '<p>¿Cómo es realmente el trabajo de una consultora de sistemas de gestión? Spoiler: hay menos papeleo y más conversaciones de las que imaginas.</p><p>Una jornada tipo en un proyecto de implantación:</p><ul><li><strong>9:00 — Sesión con el responsable de producción.</strong> No para escribir un procedimiento: para entender cómo trabaja de verdad antes de escribir nada.</li><li><strong>11:00 — Revisión de indicadores con gerencia.</strong> Media hora de datos y decisiones. Aquí es donde el sistema demuestra si sirve.</li><li><strong>12:30 — Redacción y registro en Consultify.</strong> Las horas del proyecto, las tareas por subproceso y el avance quedan registrados en nuestra plataforma en el momento.</li><li><strong>15:00 — Preparación de auditoría interna de otro cliente.</strong> Checklist, muestreo y agenda.</li></ul><p>El oficio consiste en escuchar mucho, escribir poco y bien, y conseguir que el sistema viva en la operativa, no en una carpeta.</p>', '¿Quieres formar parte del equipo o trabajar con nosotros? hola@tuconsultor.com.', 'P4 MARCA', 'TuConsultor', '2026-09-03', 'programado', '{"marca"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('auditoria-interna-8-horas', 'Auditoría interna: cómo hacerla en 8 horas sin morir en el intento', 'Una auditoría interna no necesita 3 semanas. Necesita método.', '<p>Una auditoría interna de una pyme no necesita tres semanas: necesita método. Así la resolvemos en una jornada de 8 horas para un sistema de un solo centro:</p><ul><li><strong>Antes (2 h, otro día):</strong> revisar documentación, resultados anteriores y preparar el plan de muestreo. La auditoría se gana en la preparación.</li><li><strong>9:00-9:30 — Reunión de apertura</strong> corta: agenda, alcance y reglas del juego.</li><li><strong>9:30-13:30 — Procesos operativos.</strong> En el puesto de trabajo, con la gente que hace el trabajo. Evidencias reales, no entrevistas de despacho.</li><li><strong>14:30-16:00 — Procesos de dirección y soporte:</strong> objetivos, indicadores, formación, compras.</li><li><strong>16:00-17:00 — Contraste de hallazgos y reunión de cierre.</strong> Sin sorpresas: todo hallazgo se ha comentado ya con el auditado.</li></ul><p>El informe, en 48 horas máximo. Un informe que llega un mes tarde es arqueología, no auditoría.</p>', 'También hacemos auditorías internas externalizadas. Pregúntanos.', 'P5 CONSEJOS', 'TuConsultor', '2026-09-07', 'programado', '{"consejos"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('madrid-excelente-que-es', 'Madrid Excelente: qué es y qué aporta el sello', 'Hay un sello que mide gestión, clientes y compromiso social. Y pocas empresas lo conocen.', '<p>Hay un sello de calidad que evalúa la excelencia en la gestión, la satisfacción de los clientes y el compromiso social de las empresas madrileñas, y que sorprendentemente pocas pymes conocen: <strong>Madrid Excelente</strong>, la marca de garantía del Gobierno de la Comunidad de Madrid.</p><p>Qué evalúa, en esencia:</p><ul><li>La calidad de la gestión: estrategia, procesos, resultados.</li><li>La orientación al cliente y su satisfacción demostrable.</li><li>El compromiso social y con el territorio: empleo, conciliación, sostenibilidad.</li></ul><p>Qué aporta: diferenciación frente a competidores, uso de la marca en comunicación comercial, y una evaluación externa rigurosa que sirve de diagnóstico. Para empresas que ya tienen ISO 9001 o han trabajado con EFQM, el salto es asumible: buena parte de las evidencias ya existen.</p><p>Si tu empresa opera en la Comunidad de Madrid y presume de hacer las cosas bien, este sello es la forma de demostrarlo con respaldo institucional.</p>', '¿Quieres saber si tu empresa está preparada? Hacemos el pre-diagnóstico.', 'P1 EDUCATIVO', 'TuConsultor', '2026-09-09', 'programado', '{"educativo"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('certificacion-multinorma-4-sistemas', 'Certificación multinorma: el caso de un cliente con 4 sistemas integrados', '9001 + 27001 + 45001 + 14001 en una sola auditoría integrada. Se puede.', '<p>Cuatro normas (9001, 14001, 45001 y 27001), una sola auditoría integrada, un solo sistema. Se puede, y este cliente tecnológico-industrial lo demuestra.</p><p>Las claves del proyecto:</p><ul><li><strong>Un mapa de procesos único.</strong> Cada proceso identifica sus requisitos de calidad, ambiente, seguridad laboral y seguridad de la información. Nadie gestiona "cuatro sistemas": gestiona su proceso.</li><li><strong>Riesgos en una sola matriz</strong> con las cuatro dimensiones. Un riesgo de subcontratación, por ejemplo, se evalúa a la vez en las cuatro perspectivas.</li><li><strong>Calendario único de auditorías internas</strong>, con auditores cruzados por competencia.</li><li><strong>Una revisión por la dirección</strong> anual de tres horas, no cuatro reuniones clónicas.</li></ul><p>Resultado en números: la auditoría externa integrada duró 6 jornadas frente a las 10-11 que habrían sumado por separado, con el ahorro correspondiente en coste de certificadora y en desgaste interno.</p><p>La integración no es una técnica avanzada. Es sentido común aplicado con rigor.</p>', '¿Cuántas normas gestionas y en cuántos sistemas? Si la respuesta no es "uno", hablemos.', 'P2 CASOS', 'TuConsultor', '2026-09-10', 'programado', '{"casos"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('contexto-partes-interesadas-1-pagina', 'Contexto y partes interesadas: cómo hacerlo en 1 página', 'El análisis de contexto no necesita 20 páginas. Necesita 1 bien pensada.', '<p>Hemos visto análisis de contexto de 20 páginas que no dicen nada y análisis de una página que sostienen todo el sistema. El formato que usamos y regalamos:</p><p><strong>Una tabla, cuatro columnas:</strong></p><ul><li><strong>Factor / Parte interesada:</strong> qué o quién. Ejemplo: "cliente principal (40% facturación)", "nueva normativa de envases", "dificultad para contratar oficiales".</li><li><strong>Qué espera o cómo afecta:</strong> en una frase concreta, sin literatura.</li><li><strong>Relevancia:</strong> alta / media / baja. Sé honesto: no todo es alto.</li><li><strong>Qué hacemos al respecto:</strong> la conexión con riesgos, objetivos o procesos. Esta columna es la que convierte el análisis en herramienta.</li></ul><p>Reglas: máximo 12-15 filas (si tienes 40, no has priorizado), revisión anual o cuando pase algo gordo, y prohibido copiar el del año pasado sin releerlo.</p><p>El auditor no mide el peso del documento. Mide si la empresa se conoce a sí misma.</p>', 'Guarda la plantilla. Y si quieres la nuestra en Excel, pídenosla gratis.', 'P5 CONSEJOS', 'TuConsultor', '2026-09-14', 'programado', '{"consejos"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('sistemas-gestion-ia-automatizacion', 'Sistemas de gestión con IA: lo que ya estamos automatizando (y lo que no)', 'La IA ya redacta procedimientos. La pregunta es: ¿debería?', '<p>La IA ya es capaz de redactar un procedimiento completo en treinta segundos. La pregunta interesante no es si puede, sino si debe, y para qué.</p><p><strong>Lo que ya automatizamos con criterio:</strong></p><ul><li>Borradores de documentación a partir de entrevistas reales con el cliente. La IA redacta; el consultor y el cliente corrigen lo que no refleja la realidad.</li><li>Análisis de indicadores: detección de tendencias y desviaciones que a ojo se escapan.</li><li>Preparación de auditorías: checklists por norma y muestreos.</li><li>Gestión operativa de proyectos en nuestra plataforma Consultify.</li></ul><p><strong>Lo que nos negamos a automatizar:</strong> el diagnóstico inicial, las conversaciones con la dirección, la decisión de qué es relevante para cada negocio, y la firma de un informe de auditoría. Ahí es donde un texto plausible pero equivocado hace daño de verdad.</p><p>La regla que nos funciona: la IA acelera todo lo que ya sabes hacer bien. Y amplifica todo lo que haces mal.</p>', '¿Usarías IA en tu sistema de gestión? Nos interesa tu opinión.', 'P3 OPINIÓN', 'TuConsultor', '2026-09-16', 'programado', '{"opinion"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('novedades-consultify-trimestre', 'Semáforo de cobros, sincronización de clientes, planificación: novedades de Consultify', 'Seguimos construyendo. Esto es lo nuevo de nuestra plataforma este trimestre.', '<p>Seguimos construyendo Consultify, nuestra plataforma de gestión para consultoría, y este trimestre han llegado tres novedades de las que estamos especialmente orgullosos:</p><ul><li><strong>Semáforo de cobros conectado a la contabilidad.</strong> Cada cliente muestra en verde, amarillo o rojo el estado de sus facturas, con actualización diaria automática. Se acabó perseguir Excel de cobros.</li><li><strong>Sincronización automática de clientes</strong> con nuestra plataforma de comunicación: cada alta o cambio se refleja al instante, sin dobles capturas.</li><li><strong>Planificación por modelos de servicio:</strong> los cuatro modelos de colaboración se ven y editan lado a lado por norma, con las horas por proceso y perfil de consultor.</li></ul><p>Todo nace de la misma filosofía: cada hora que no gastamos en administración es una hora más de consultoría real para nuestros clientes.</p><p>Y sí, lo construimos nosotros. Con mucho café y mucho cariño, en Madrid.</p>', '¿Quieres ver Consultify por dentro? Pide una demo en consultify.pro.', 'P4 MARCA', 'TuConsultor', '2026-09-17', 'programado', '{"marca"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('objetivos-calidad-5-ejemplos', 'Objetivos de calidad que no dan vergüenza: 5 ejemplos reales', '"Mejorar la satisfacción del cliente" no es un objetivo. Es un deseo.', '<p>"Mejorar la satisfacción del cliente" no es un objetivo: es un deseo. Un objetivo de verdad tiene meta numérica, plazo, responsable y plan. Cinco ejemplos reales (adaptados) que sí funcionan:</p><ul><li><strong>Reducir las reclamaciones por errores de envío del 2,1% al 1,2%</strong> de los pedidos antes del 31/12, rediseñando el control de expediciones. Responsable: jefe de logística.</li><li><strong>Bajar el plazo medio de respuesta a ofertas de 9 a 4 días laborables</strong> en el primer semestre, con plantillas y aprobación delegada.</li><li><strong>Conseguir que el 100% de las no conformidades se cierren en menos de 45 días</strong> (hoy: media de 92).</li><li><strong>Reducir el consumo eléctrico por unidad producida un 8%</strong> este ejercicio (objetivo integrado con 14001).</li><li><strong>Formar e independizar a un segundo auditor interno</strong> antes de junio, para eliminar el cuello de botella actual.</li></ul><p>El test: si en la revisión de junio no puedes decir cuánto llevas conseguido con un número, no era un objetivo.</p>', 'Guarda estos ejemplos para tu próxima definición de objetivos.', 'P5 CONSEJOS', 'TuConsultor', '2026-09-21', 'programado', '{"consejos"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('iso-45001-mas-alla-cumplimiento', 'ISO 45001: seguridad y salud más allá del cumplimiento legal', 'La prevención de riesgos laborales ya la tienes. La 45001 es otra cosa.', '<p>"Ya tenemos prevención de riesgos, ¿para qué la 45001?" Es la objeción más habitual y nace de una confusión: la prevención legal (plan de prevención, evaluaciones, vigilancia de la salud) es el suelo obligatorio. La <strong>ISO 45001</strong> es un sistema de gestión: otra cosa.</p><p>Las diferencias que importan:</p><ul><li>La ley te exige evaluar riesgos; la 45001 te exige además <strong>gestionar oportunidades</strong> de mejora de la seguridad y salud, y demostrar mejora continua.</li><li>La ley se centra en el cumplimiento; la norma exige <strong>liderazgo visible de la dirección</strong> y consulta y participación real de la plantilla, con evidencias.</li><li>La 45001 integra la seguridad en la operación diaria: compras, subcontratas, cambios, emergencias, no como servicio externo que visita dos veces al año.</li></ul><p>El resultado medible en las empresas que la implantan bien: menos siniestralidad, menos absentismo y mejor posición en licitaciones y homologaciones de cliente donde cada vez más se exige.</p>', '¿Tienes la prevención externalizada y desconectada del negocio? Hablemos.', 'P1 EDUCATIVO', 'TuConsultor', '2026-09-23', 'programado', '{"educativo"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('sistema-abandonado-2-anos', 'Lo que pasa cuando un sistema se abandona 2 años (historia real)', 'Nos llamaron 3 semanas antes de la auditoría de renovación. El sistema llevaba 2 años parado.', '<p>Nos llamaron tres semanas antes de su auditoría de renovación. El responsable de calidad se había ido hacía dos años y nadie había asumido el sistema: sin auditorías internas, sin revisión por la dirección, con indicadores congelados en 2024.</p><p>Fuimos honestos desde el minuto uno: en tres semanas no se reconstruyen dos años, y maquillar registros ni es ético ni funciona (los auditores lo detectan siempre). Lo que sí se podía hacer:</p><ul><li>Aplazar la auditoría seis semanas negociando con la certificadora. Se aceptó.</li><li>Hacer de verdad, aunque comprimido, lo esencial: auditoría interna real, revisión por la dirección real, plan de acciones honesto que reconociera el parón.</li><li>Presentarse con transparencia: "el sistema estuvo desatendido, esto es lo que hemos hecho y este es el plan".</li></ul><p>Resultado: renovación con dos no conformidades menores y una felicitación del auditor por la honestidad del enfoque. Y una lección para el cliente: el sistema ahora tiene dos responsables, no uno.</p>', '¿Tu sistema lleva tiempo parado? Aún hay solución, pero cuanto antes, mejor.', 'P2 CASOS', 'TuConsultor', '2026-09-24', 'programado', '{"casos"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('cuenta-atras-90-dias-auditoria', 'Preparar la auditoría de certificación: cuenta atrás de 90 días', '90, 60, 30 días: qué hacer en cada hito antes de la auditoría.', '<p>La auditoría de certificación no se prepara la semana antes. Se prepara con una cuenta atrás de 90 días:</p><p><strong>Día -90:</strong></p><ul><li>Auditoría interna completa de todo el alcance. Es tu ensayo general: cuanto más exigente, mejor.</li><li>Verificar que hay registros de al menos 3 meses de funcionamiento real del sistema.</li></ul><p><strong>Día -60:</strong></p><ul><li>Cerrar las acciones derivadas de la auditoría interna (las importantes, con evidencias).</li><li>Celebrar la revisión por la dirección con todos los elementos de entrada.</li><li>Confirmar con la certificadora alcance, fechas y agenda de la fase 1.</li></ul><p><strong>Día -30:</strong></p><ul><li>Resolver los hallazgos de la fase 1 documental.</li><li>Sesión breve con el equipo: qué es una auditoría, qué preguntarán, y la regla de oro (responder con la verdad y con evidencias, no con lo que "queda bien").</li></ul><p><strong>Día -7:</strong> logística, agenda interna y tranquilidad. Si los 90 días se hicieron, la auditoría es un trámite exigente, no un examen sorpresa.</p>', 'Guarda esta cuenta atrás. Y si quieres que la ejecutemos contigo, aquí estamos.', 'P5 CONSEJOS', 'TuConsultor', '2026-09-28', 'programado', '{"consejos"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('calidad-no-es-burocracia', 'Calidad no es burocracia: contra el mito del papeleo ISO', '"La ISO es papeleo" es la frase que más escucho. Y la que más rabia me da.', '<p>"La ISO es puro papeleo." Es la frase que más escuchamos en primeras reuniones, y la que más rabia nos da. No porque sea mentira siempre, sino porque a veces es verdad, y la culpa no es de la norma.</p><p>La ISO 9001 actual exige muy poca documentación obligatoria. Muchísima menos de lo que la gente cree. El papeleo asfixiante viene de otro sitio:</p><ul><li>De consultoras que venden manuales de 200 páginas porque el kilo de papel aparenta valor.</li><li>De la creencia de que "por si acaso el auditor lo pide" justifica cualquier registro.</li><li>De sistemas heredados que nadie se atreve a podar.</li></ul><p>Nuestra experiencia tras cientos de auditorías: los mejores sistemas que hemos visto caben en poco más de una carpeta, y las empresas que los tienen no distinguen entre "trabajar" y "cumplir la ISO" porque son la misma cosa.</p><p>Si tu sistema te estorba, el problema no es la calidad. Es el diseño de tu sistema. Y eso tiene arreglo: se llama simplificación, y es de nuestros proyectos favoritos.</p>', '¿Tu sistema pesa demasiado? Pide una revisión de simplificación.', 'P3 OPINIÓN', 'TuConsultor', '2026-09-30', 'programado', '{"opinion"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

insert into public.blog_posts (slug, titulo, extracto, contenido_html, cta, pilar, autor, fecha_publicacion, estado, tags)
values ('balance-q3-2026', 'Q3 2026 en TuConsultor: certificaciones, aprendizajes y lo que viene', 'Trimestre cerrado. Estos son los números y las lecciones.', '<p>Cerramos el tercer trimestre de 2026 y, como cada trimestre, toca ejercicio de transparencia: números, lecciones y lo que viene.</p><p><strong>Lo que ha dado de sí el trimestre:</strong> nuevos proyectos de certificación en marcha, auditorías acompañadas superadas, y un verano en el que Consultify, nuestra plataforma, ha seguido creciendo con el semáforo de cobros y la sincronización automática de clientes.</p><p><strong>La lección del trimestre:</strong> las normas "nuevas" ya no son nicho. Las consultas sobre ISO 42001 (gestión de IA) y sobre planes de igualdad se han multiplicado, y la conversación con los clientes está cambiando: ya no preguntan solo "qué necesito para certificarme", sino "cómo hago que esto sirva de verdad". Nos encanta ese cambio.</p><p><strong>Lo que viene en Q4:</strong> más contenido práctico en este blog cada semana, novedades de plataforma y la campaña de renovaciones de final de año, que ya está en marcha.</p><p>Gracias por leernos y por confiar. Desde 2006, gestionando con el corazón.</p>', '¿Arrancamos juntos el Q4? hola@tuconsultor.com.', 'P4 MARCA', 'TuConsultor', '2026-10-01', 'programado', '{"marca"}')
on conflict (slug) do update set
  titulo=excluded.titulo, extracto=excluded.extracto, contenido_html=excluded.contenido_html,
  cta=excluded.cta, pilar=excluded.pilar, autor=excluded.autor,
  fecha_publicacion=excluded.fecha_publicacion, estado=excluded.estado, tags=excluded.tags;

commit;

-- Comprobación: nº de posts y rango de fechas
select count(*) as total, min(fecha_publicacion) as primera, max(fecha_publicacion) as ultima from public.blog_posts;